(function(){
'use strict';
if(window.__DG_V53_FINISH__)return;window.__DG_V53_FINISH__=true;
const $=id=>document.getElementById(id);let dashGroups=[],dashDays=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function css(){if($('dg53css'))return;const s=document.createElement('style');s.id='dg53css';s.textContent=`.dg53-dashboard{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:0 0 14px}.dg53-kpi{border:0;border-radius:16px;padding:14px;text-align:left;font-weight:800;cursor:pointer}.dg53-kpi strong{display:block;font-size:28px;margin-top:4px}.dg53-kpi.red{background:#fee2e2;color:#991b1b}.dg53-kpi.orange{background:#ffedd5;color:#9a3412}.dg53-kpi.green{background:#dcfce7;color:#166534}.dg53-kpi.loading{background:#f3f4f6;color:#6b7280}.dg53-hint{font-size:12px;color:#166534;font-weight:700;margin:-5px 0 10px 2px}.dg53-target{scroll-margin-top:12px}.dg53-day-list{display:grid;gap:10px}.dg53-day-emp{border:1px solid #e5e7eb;border-radius:14px;padding:12px}.dg53-day-row{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-top:1px solid #e5e7eb}.dg53-day-row:first-of-type{border-top:0}.status.ok{background:#dcfce7!important;color:#166534!important}.status.warn{background:#ffedd5!important;color:#9a3412!important}.status.error{background:#fee2e2!important;color:#991b1b!important}.status.info{background:#e0f2fe!important;color:#075985!important}@media(max-width:700px){.dg53-dashboard{grid-template-columns:1fr}.dg53-kpi{padding:12px}.dg53-kpi strong{font-size:24px}.dg53-day-row{flex-direction:column;gap:2px}}`;document.head.appendChild(s)}
function regieCard(){const boss=$('bossView');if(!boss)return null;return [...boss.querySelectorAll(':scope > .card')].find(c=>{const h=c.querySelector('.dg48-head h2,:scope > h2');return h&&h.textContent.trim()==='Regieberichte'})||null}
function openRegie(){const c=regieCard();if(!c)return null;const body=c.querySelector('.dg48-body');if(body&&body.classList.contains('hidden')){body.classList.remove('hidden');const b=c.querySelector('.dg48-toggle');if(b)b.textContent='−'}return c}
async function jumpRegie(view){const c=openRegie();if(!c)return;if(typeof window.loadRegieReports==='function')await window.loadRegieReports(view);setTimeout(()=>{const result=$('regieResult');(result||c).scrollIntoView({behavior:'smooth',block:'start'})},80)}
function ensureDayTarget(){let t=$('dg53OpenDaysTarget');if(t)return t;const group=$('dg48EmployeeClosures');if(!group)return null;const body=group.querySelector('.dg48-body');if(body&&body.classList.contains('hidden')){body.classList.remove('hidden');const b=group.querySelector('.dg48-toggle');if(b)b.textContent='−'}t=document.createElement('div');t.id='dg53OpenDaysTarget';t.className='dg48-subsection dg53-target';t.innerHTML='<h3>Offene Tagesabschlüsse</h3><div class="muted small">Mitarbeiter und noch offene Arbeitstage im aktuellen Monat.</div><div id="dg53OpenDaysList" class="dg53-day-list" style="margin-top:10px"></div>';body?body.prepend(t):group.appendChild(t);return t}
function renderOpenDays(){const t=ensureDayTarget();if(!t)return;const out=$('dg53OpenDaysList');const rows=(dashDays||[]).map(emp=>{const days=(emp.days||[]).filter(d=>!d.closed);if(!days.length)return'';return '<div class="dg53-day-emp"><strong>'+esc(emp.employee)+'</strong>'+days.map(d=>'<div class="dg53-day-row"><span>🔴 '+esc(typeof formatDateDE==='function'?formatDateDE(d.date):d.date)+'</span><span class="muted small">'+esc(typeof formatHours==='function'?formatHours(d.hours||0):d.hours)+' Std. · '+Number(d.entryCount||0)+' Eintrag/Einträge</span></div>').join('')+'</div>'}).join('');out.innerHTML=rows||'<div class="status ok">✓ Keine offenen Tagesabschlüsse im aktuellen Monat.</div>'}
function jumpDays(){const t=ensureDayTarget();if(!t)return;renderOpenDays();t.scrollIntoView({behavior:'smooth',block:'start'})}
function addDashboard(){const boss=$('bossView');if(!boss||$('dg53Dashboard'))return;const d=document.createElement('div');d.id='dg53Dashboard';d.className='dg53-dashboard';d.innerHTML='<button class="dg53-kpi loading" id="dg53Run" type="button"><span>Laufende Aufträge</span><strong>…</strong></button><button class="dg53-kpi loading" id="dg53Open" type="button"><span>Offene Regieberichte</span><strong>…</strong></button><button class="dg53-kpi loading" id="dg53Days" type="button"><span>Offene Tagesabschlüsse</span><strong>…</strong></button>';boss.prepend(d);$('dg53Run').onclick=()=>jumpRegie('Laufend');$('dg53Open').onclick=()=>jumpRegie('Abgeschlossen');$('dg53Days').onclick=jumpDays;refreshDashboard()}
async function refreshDashboard(){if(!navigator.onLine)return;try{let groups=await api(chefPayload({action:'getRegieReports',status:'Offen',year:0,month:0}));if(typeof mergeRegieGroups==='function')groups=mergeRegieGroups(groups||[]);dashGroups=groups||[];const running=dashGroups.filter(g=>(g.jobStatus||'Abgeschlossen')==='Laufend').length;const open=dashGroups.filter(g=>(g.jobStatus||'Abgeschlossen')!=='Laufend').length;setKpi('dg53Run',running,running?'red':'green');setKpi('dg53Open',open,open?'orange':'green');const n=new Date();dashDays=await api(chefPayload({action:'getBossDayClosures',year:n.getFullYear(),month:n.getMonth()+1}))||[];let missing=0;dashDays.forEach(e=>(e.days||[]).forEach(d=>{if(!d.closed)missing++}));setKpi('dg53Days',missing,missing?'red':'green');if($('dg53OpenDaysTarget'))renderOpenDays()}catch(e){['dg53Run','dg53Open','dg53Days'].forEach(id=>{const x=$(id);if(x){x.className='dg53-kpi loading';x.querySelector('strong').textContent='–'}})}}
function setKpi(id,n,c){const x=$(id);if(!x)return;x.className='dg53-kpi '+c;x.querySelector('strong').textContent=String(n)}
function employeeHint(){const b=$('employeeTimeBank');if(!b||$('dg53MonthHint'))return;const h=document.createElement('div');h.id='dg53MonthHint';h.className='dg53-hint';h.textContent='Aktueller Monat · inklusive Korrekturen durch das Büro';b.insertAdjacentElement('afterend',h)}
const oldBoss=window.showBoss;if(typeof oldBoss==='function')window.showBoss=function(){const r=oldBoss.apply(this,arguments);setTimeout(()=>{addDashboard();refreshDashboard()},0);return r};css();employeeHint();if(!$('bossView')?.classList.contains('hidden'))addDashboard();document.title='DG Zeiterfassung v53';const lv=document.querySelector('.login-card .center.muted.small');if(lv)lv.textContent='Version 53';const hv=document.querySelector('.hero .head-row strong');if(hv)hv.textContent='Zeiterfassung · v53';
})();