(function(){
'use strict';
if(window.__DG_V53_FINISH__)return;window.__DG_V53_FINISH__=true;
const $=id=>document.getElementById(id);
function css(){if($('dg53css'))return;const s=document.createElement('style');s.id='dg53css';s.textContent=`
.dg53-dashboard{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:0 0 14px}.dg53-kpi{border:0;border-radius:16px;padding:14px;text-align:left;font-weight:800;cursor:pointer}.dg53-kpi strong{display:block;font-size:28px;margin-top:4px}.dg53-kpi.red{background:#fee2e2;color:#991b1b}.dg53-kpi.orange{background:#ffedd5;color:#9a3412}.dg53-kpi.green{background:#dcfce7;color:#166534}.dg53-kpi.loading{background:#f3f4f6;color:#6b7280}.dg53-hint{font-size:12px;color:#166534;font-weight:700;margin:-5px 0 10px 2px}.status.ok{background:#dcfce7!important;color:#166534!important}.status.warn{background:#ffedd5!important;color:#9a3412!important}.status.error{background:#fee2e2!important;color:#991b1b!important}.status.info{background:#e0f2fe!important;color:#075985!important}@media(max-width:700px){.dg53-dashboard{grid-template-columns:1fr}.dg53-kpi{padding:12px}.dg53-kpi strong{font-size:24px}}
`;document.head.appendChild(s)}
function openCard(id){const card=$(id);if(!card)return;const body=card.querySelector('.dg48-body');if(body&&body.classList.contains('hidden')){body.classList.remove('hidden');const b=card.querySelector('.dg48-toggle');if(b)b.textContent='−'}card.scrollIntoView({behavior:'smooth',block:'start'})}
function addDashboard(){const boss=$('bossView');if(!boss||$('dg53Dashboard'))return;const d=document.createElement('div');d.id='dg53Dashboard';d.className='dg53-dashboard';d.innerHTML='<button class="dg53-kpi loading" id="dg53Run" type="button"><span>Laufende Aufträge</span><strong>…</strong></button><button class="dg53-kpi loading" id="dg53Open" type="button"><span>Offene Regieberichte</span><strong>…</strong></button><button class="dg53-kpi loading" id="dg53Days" type="button"><span>Offene Tagesabschlüsse</span><strong>…</strong></button>';boss.prepend(d);$('dg53Run').onclick=()=>openCard('dg48EmployeeClosures')||openRegie();$('dg53Open').onclick=openRegie;$('dg53Days').onclick=()=>openCard('dg48EmployeeClosures');refreshDashboard()}
function openRegie(){const boss=$('bossView');if(!boss)return;const cards=[...boss.querySelectorAll(':scope > .card')];const c=cards.find(x=>{const h=x.querySelector('.dg48-head h2,:scope > h2');return h&&h.textContent.trim()==='Regieberichte'});if(c){const body=c.querySelector('.dg48-body');if(body&&body.classList.contains('hidden')){body.classList.remove('hidden');const b=c.querySelector('.dg48-toggle');if(b)b.textContent='−'}c.scrollIntoView({behavior:'smooth',block:'start'})}}
async function refreshDashboard(){if(!navigator.onLine)return;try{let groups=await api(chefPayload({action:'getRegieReports',status:'Offen',year:0,month:0}));if(typeof mergeRegieGroups==='function')groups=mergeRegieGroups(groups||[]);const running=(groups||[]).filter(g=>(g.jobStatus||'Abgeschlossen')==='Laufend').length;const open=(groups||[]).filter(g=>(g.jobStatus||'Abgeschlossen')!=='Laufend').length;setKpi('dg53Run',running,running?'red':'green');setKpi('dg53Open',open,open?'orange':'green');const n=new Date();const days=await api(chefPayload({action:'getBossDayClosures',year:n.getFullYear(),month:n.getMonth()+1}));let missing=0;(days||[]).forEach(e=>(e.days||[]).forEach(d=>{if(!d.closed)missing++}));setKpi('dg53Days',missing,missing?'red':'green')}catch(e){['dg53Run','dg53Open','dg53Days'].forEach(id=>{const x=$(id);if(x){x.className='dg53-kpi loading';x.querySelector('strong').textContent='–'}})}}
function setKpi(id,n,c){const x=$(id);if(!x)return;x.className='dg53-kpi '+c;x.querySelector('strong').textContent=String(n)}
function employeeHint(){const b=$('employeeTimeBank');if(!b||$('dg53MonthHint'))return;const h=document.createElement('div');h.id='dg53MonthHint';h.className='dg53-hint';h.textContent='Aktueller Monat · inklusive Korrekturen durch das Büro';b.insertAdjacentElement('afterend',h)}
const oldBoss=window.showBoss;if(typeof oldBoss==='function')window.showBoss=function(){const r=oldBoss.apply(this,arguments);setTimeout(()=>{addDashboard();refreshDashboard()},0);return r};
css();employeeHint();if(!$('bossView')?.classList.contains('hidden'))addDashboard();document.title='DG Zeiterfassung v53';const lv=document.querySelector('.login-card .center.muted.small');if(lv)lv.textContent='Version 53';const hv=document.querySelector('.hero .head-row strong');if(hv)hv.textContent='Zeiterfassung · v53';
})();