(function(){
'use strict';
if(window.__DG_V57_PATCH__)return;window.__DG_V57_PATCH__=true;
const $=id=>document.getElementById(id);
const esc57=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt57=v=>typeof formatHours==='function'?formatHours(v):Number(v||0).toFixed(2).replace('.',',');
function addCss(){if($('dg57css'))return;const s=document.createElement('style');s.id='dg57css';s.textContent=`
.dg57-transmitted{margin-top:5px;font-size:12px;font-weight:700;color:#475569}.dg57-transmitted.chef{color:#1e3a5f}.dg57-transmitted.employee{color:#64748b}
`;document.head.appendChild(s)}
function onlyDate(v){const x=String(v||'').trim();return x.includes(' ')?x.split(' ')[0]:x}
function addLine(host,text,chef){if(!host||!text)return;let x=host.querySelector(':scope > .dg57-transmitted');if(!x){x=document.createElement('div');x.className='dg57-transmitted '+(chef?'chef':'employee');host.appendChild(x)}x.textContent=(chef?'Übertragen am ':'Übertragen am ')+text}
function decorateEmployeeDay(){const rows=[...document.querySelectorAll('#entries > .entry')],data=(typeof lastDayData!=='undefined'&&lastDayData&&lastDayData.entries)||[];rows.forEach((row,i)=>{row.querySelectorAll('.dg55-supplement-note').forEach(x=>x.remove());const e=data[i]||{};const d=e.transmittedDate||onlyDate(e.supplementCreatedAt);if(d)addLine(row,d,false)})}
const oldRender=window.renderDay;if(typeof oldRender==='function')window.renderDay=function(){const r=oldRender.apply(this,arguments);decorateEmployeeDay();return r};
setTimeout(decorateEmployeeDay,0);

const oldLoadMonth=window.loadMonth;if(typeof oldLoadMonth==='function')window.loadMonth=async function(){const r=await oldLoadMonth.apply(this,arguments);try{const a=auth();if(!navigator.onLine||!a.employee||!a.pin)return r;const data=await api({action:'getMonthData',employee:a.employee,pin:a.pin,year:Number($('empYear').value),month:Number($('empMonth').value)});const byDate={};(data.rows||[]).forEach(x=>{(byDate[x.date]||(byDate[x.date]=[])).push(x)});[...document.querySelectorAll('#monthResult details.entry')].forEach(detail=>{const summary=detail.querySelector('summary');const m=(summary&&summary.textContent||'').match(/(\d{2}\.\d{2}\.\d{4})/);if(!m)return;const p=m[1].split('.'),iso=p[2]+'-'+p[1]+'-'+p[0],items=byDate[iso]||[],rows=[...detail.querySelectorAll(':scope > div .entry')];rows.forEach((row,i)=>{const d=(items[i]||{}).transmittedDate;if(d)addLine(row,d,false)})})}catch(_e){}return r};

window.renderBossEntries=function(x){return (x.entries||[]).map((e,i)=>'<div class="entry"><strong>'+formatDateDE(e.date)+' · '+esc57(e.customer)+' · '+fmt57(e.hours)+' Std.</strong>'+(e.isAdditionalAssignment?' · Mitarbeit':'')+(e.isSupplement?' <span class="dg55-supplement">NACHTRAG</span>':'')+'<br><span class="muted">'+esc57(e.activity||'')+'</span>'+(e.transmittedAt?'<div class="dg57-transmitted chef">Übertragen am '+esc57(e.transmittedAt)+'</div>':'')+'<div class="admin-actions" style="margin-top:8px"><button class="btn secondary" onclick="openObjectView('+i+')">🏢 Objekt aufrufen</button><button class="btn secondary" onclick="setBossDetailTab(\'adjust\')">± Stunden anpassen</button></div></div>').join('')||'<div class="muted">Keine Aufträge.</div>'};

window.openObjectView=async function(entryIndex){const x=(window.__bossMonthRows||[])[bossDetailIndex],e=(x&&x.entries||[])[entryIndex];if(!e)return;try{setMessage('bossStatus','Objekt wird geladen …','info');const o=await api(chefPayload({action:'getObjectReports',objectId:e.objectId||'',customer:e.customer}));let h=bossToolbar(x)+'<button class="btn secondary" onclick="renderBossActions()">← Zurück zu '+esc57(x.employee)+'</button><div class="object-summary"><strong>🏢 '+esc57(o.displayName||e.customer)+'</strong><br>Berichte: '+Number(o.reportCount||0)+' · Gesamtstunden: '+fmt57(o.totalHours)+' · Mitarbeiter: '+esc57((o.employees||[]).join(', '))+'</div>';h+=(o.reports||[]).map(r=>'<div class="report-card"><strong>'+formatDateDE(r.date)+' · '+esc57(r.employee)+' · '+fmt57(r.hours)+' Std.</strong>'+(r.isSupplement?' <span class="dg55-supplement">NACHTRAG</span>':'')+'<div class="report-meta">'+esc57(r.start)+'–'+esc57(r.end)+' · '+esc57(r.regieStatus)+'</div><div>'+esc57(r.activity||'')+'</div>'+(r.transmittedAt?'<div class="dg57-transmitted chef">Übertragen am '+esc57(r.transmittedAt)+'</div>':'')+(r.materialUsed?'<div class="report-meta"><strong>Material:</strong> '+esc57(r.material||'')+'</div>':'')+'<div class="report-actions">'+reportLinks(r)+'</div></div>').join('');$('bossResult').innerHTML=h;clearMessage('bossStatus')}catch(err){setMessage('bossStatus',err.message,'error')}};

const oldClosures=window.renderBossDayClosuresV48;if(typeof oldClosures==='function')window.renderBossDayClosuresV48=function(rows){const r=oldClosures.apply(this,arguments);let dayIndex=0;const dayCards=[...document.querySelectorAll('#dg48DayResult .dg48-day')];(rows||[]).forEach(emp=>(emp.days||[]).forEach(day=>{const card=dayCards[dayIndex++];if(!card)return;const reports=[...card.querySelectorAll('.dg49-report')];(day.reports||[]).forEach((rep,i)=>{if(reports[i]&&rep.transmittedAt)addLine(reports[i],rep.transmittedAt,true)})}));return r};

const oldRegie=window.loadRegieReports;if(typeof oldRegie==='function')window.loadRegieReports=async function(view){const r=await oldRegie.apply(this,arguments);try{if(!navigator.onLine)return r;const isBilled=view==='Abgerechnet',isRunning=view==='Laufend';let groups=await api(chefPayload({action:'getRegieReports',status:isBilled?'Abgerechnet':'Offen',year:isBilled?(Number($('regieYear').value)||0):0,month:isBilled?(Number($('regieMonth').value)||0):0}));groups=typeof mergeRegieGroups==='function'?mergeRegieGroups(groups||[]):(groups||[]);if(!isBilled)groups=groups.filter(g=>isRunning?(g.jobStatus==='Laufend'):(g.jobStatus!=='Laufend'));const cards=[...document.querySelectorAll('#regieResult > .report-card')];groups.forEach((g,gi)=>{const card=cards[gi];if(!card)return;const entries=[...card.querySelectorAll('details .entry')];(g.reports||[]).forEach((rep,ri)=>{const row=entries[ri];if(!row)return;row.querySelectorAll('.dg55-supplement-note').forEach(x=>x.remove());if(rep.transmittedAt)addLine(row,rep.transmittedAt,true)})})}catch(_e){}return r};

addCss();document.title='DG Zeiterfassung v57';const lv=document.querySelector('.login-card .center.muted.small');if(lv)lv.textContent='Version 57';const hv=document.querySelector('.hero .head-row strong');if(hv)hv.textContent='Zeiterfassung · v57';
})();