(function(){
'use strict';
if(window.__DG_V62_PLACES__)return;window.__DG_V62_PLACES__=true;
const $=id=>document.getElementById(id);
// Google Maps Browser-Key wird lokal im Browser hinterlegt, nicht im Repository.
const STORAGE_KEY='dg_maps_browser_key';
function getMapsKey(){return String(localStorage.getItem(STORAGE_KEY)||'').trim()}
window.dg62SetMapsKey=function(key){key=String(key||'').trim();if(!key){localStorage.removeItem(STORAGE_KEY);alert('Google Maps API-Key wurde entfernt.');return}localStorage.setItem(STORAGE_KEY,key);alert('Google Maps API-Key wurde auf diesem Gerät gespeichert. Bitte App neu laden.')};
let loadPromise=null;
function addCss(){if($('dg62PlacesCss'))return;const s=document.createElement('style');s.id='dg62PlacesCss';s.textContent=`.pac-container{z-index:20000!important}.dg62-place-note{font-size:12px;color:#64748b;margin-top:5px}.dg62-place-ok{color:#166534!important}`;document.head.appendChild(s)}
function loadGoogle(){if(window.google&&google.maps&&google.maps.places)return Promise.resolve();if(loadPromise)return loadPromise;loadPromise=new Promise((resolve,reject)=>{const key=getMapsKey();if(!key)return reject(new Error('Google Maps API-Key ist auf diesem Gerät noch nicht hinterlegt.'));const cb='dgPlacesReady_'+Date.now();window[cb]=()=>{delete window[cb];resolve()};const sc=document.createElement('script');sc.async=true;sc.defer=true;sc.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&libraries=places&language=de&region=DE&callback='+cb;sc.onerror=()=>reject(new Error('Google Places konnte nicht geladen werden.'));document.head.appendChild(sc)});return loadPromise}
function attachAutocomplete(input,note){if(!input||input.dataset.dgPlaces==='1')return;loadGoogle().then(()=>{if(!(google&&google.maps&&google.maps.places))return;const ac=new google.maps.places.Autocomplete(input,{componentRestrictions:{country:'de'},fields:['formatted_address','address_components','name','place_id'],types:['address']});ac.addListener('place_changed',()=>{const p=ac.getPlace();if(p&&p.formatted_address)input.value=p.formatted_address;const comps={};(p.address_components||[]).forEach(c=>(c.types||[]).forEach(t=>comps[t]=c.long_name));input.dataset.placeId=p.place_id||'';input.dataset.street=[comps.route||'',comps.street_number||''].filter(Boolean).join(' ');input.dataset.postalCode=comps.postal_code||'';input.dataset.city=comps.locality||comps.postal_town||comps.administrative_area_level_3||'';if(note){note.textContent='✓ Adresse aus Google übernommen'+(input.dataset.postalCode||input.dataset.city?' · '+[input.dataset.postalCode,input.dataset.city].filter(Boolean).join(' '):'');note.classList.add('dg62-place-ok')}});input.dataset.dgPlaces='1';if(note)note.textContent='Adresse tippen – Google schlägt passende Adressen vor'}).catch(e=>{if(note)note.textContent=e.message||'Adressvorschläge nicht verfügbar.'})}
function ensureCalendar(){addCss();const input=$('dg62Address');if(!input)return;let note=$('dg62PlacesNote');if(!note){note=document.createElement('div');note.id='dg62PlacesNote';note.className='dg62-place-note';input.insertAdjacentElement('afterend',note)}attachAutocomplete(input,note)}
function ensureOtherAddressFields(){document.querySelectorAll('input').forEach(input=>{if(input.id==='dg62Address')return;const key=((input.id||'')+' '+(input.name||'')+' '+(input.placeholder||'')).toLowerCase();if(!/(adresse|straße|strasse|anschrift)/.test(key))return;if(input.dataset.dgPlaces==='1')return;let note=input.nextElementSibling;if(!(note&&note.classList&&note.classList.contains('dg62-place-note'))){note=document.createElement('div');note.className='dg62-place-note';input.insertAdjacentElement('afterend',note)}attachAutocomplete(input,note)})}
function setVersion(){document.title='DG Zeiterfassung v62.18';const lv=document.querySelector('.login-card .center.muted.small');if(lv)lv.textContent='Version 62.18';const hv=document.querySelector('.hero .head-row strong');if(hv)hv.textContent='Zeiterfassung · v62.18'}
const oldEdit=window.dg62Edit;if(typeof oldEdit==='function')window.dg62Edit=function(){const r=oldEdit.apply(this,arguments);setTimeout(ensureCalendar,0);return r};const oldNew=window.dg62New;if(typeof oldNew==='function')window.dg62New=function(){const r=oldNew.apply(this,arguments);setTimeout(ensureCalendar,0);return r};const oldBoss=window.showBoss;if(typeof oldBoss==='function')window.showBoss=function(){const r=oldBoss.apply(this,arguments);setTimeout(()=>{ensureCalendar();ensureOtherAddressFields()},350);return r};setTimeout(()=>{ensureCalendar();ensureOtherAddressFields();setVersion()},700);
})();
