(function(){
'use strict';
if(window.__DG_V62_PATCH__)return;window.__DG_V62_PATCH__=true;
const $=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let weekStart='',workers=[],events=[],adminRows=[],editId='';
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function parse(s){const p=String(s||'').split('-').map(Number);return new Date(p[0],p[1]-1,p[2],12)}
function monday(s){const d=s?parse(s):new Date(),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return iso(d)}
function add(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function fmtDate(s){return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(parse(s))}
function setSt(id,text,type='info'){const e=$(id);if(e){e.className='status '+type;e.textContent=text}}
function mins(t){const m=/^(\d{1,2}):(\d{2})$/.exec(String(t||''));return m?Number(m[1])*60+Number(m[2]):0}
function eventHours(e){let a=mins(e.start),b=mins(e.end);if(b<a)b+=1440;return Math.max(0,b-a)/60}
function fmtH(v){return Number(v||0).toFixed(2).replace('.',',')}
function targetHours(name,dayIndex){const n=String(name||'').trim();const r=adminRows.find(x=>String(x.name||'').trim()===n)||adminRows.find(x=>String((x.firstName||'')+' '+(x.lastName||'')).trim()===n);if(!r)return 0;return Number([r.monday,r.tuesday,r.wednesday,r.thursday,r.friday][dayIndex]||0)}
function removeLegacyWarnings(){['dg58BackendStatus','dg59BackendStatus','dg60BackendStatus','dg61BackendStatus'].forEach(id=>{const x=$(id);if(x)x.remove()})}
function closeRegie(){const heads=[...document.querySelectorAll('#bossView .dg48-head')];const h=heads.find(x=>String(x.textContent||'').includes('Regieberichte'));if(!h)return;const card=h.closest('.card'),body=card&&card.querySelector(':scope > .dg48-body'),btn=h.querySelector('.dg48-toggle');if(body)body.classList.add('hidden');if(btn)btn.textContent='+'}
function css(){if($('dg62css'))return;const s=document.createElement('style');s.id='dg62css';s.textContent=`#dg58BackendStatus,#dg59BackendStatus,#dg60BackendStatus,#dg61BackendStatus{display:none!important}.dg62-summary{cursor:pointer;font-size:21px;font-weight:800;list-style:none}.dg62-summary::-webkit-details-marker{display:none}.dg62-summary:before{content:"▸";display:inline-block;width:25px}.dg62-main[open]>.dg62-summary:before{content:"▾"}.dg62-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.dg62-toolbar .btn{width:auto}.dg62-day{border:1px solid #d1d5db;border-radius:13px;margin:10px 0;overflow:hidden}.dg62-dayhead{background:#f1f5f9;padding:11px 13px;font-weight:900}.dg62-person{display:grid;grid-template-columns:190px 1fr;border-top:1px solid #e5e7eb;min-height:64px}.dg62-person.dg62-under{border-left:6px solid #dc2626;background:#fef2f2}.dg62-person.dg62-ok{border-left:6px solid #16a34a;background:#f0fdf4}.dg62-personname{font-weight:800;padding:11px;background:#fafafa;border-right:1px solid #e5e7eb}.dg62-under .dg62-personname{background:#fee2e2}.dg62-ok .dg62-personname{background:#dcfce7}.dg62-hours{font-size:12px;margin-top:4px;font-weight:800}.dg62-under .dg62-hours{color:#991b1b}.dg62-ok .dg62-hours{color:#166534}.dg62-events{padding:7px;min-height:58px;cursor:pointer}.dg62-empty{color:#94a3b8;font-size:12px;padding:8px}.dg62-event{border-left:5px solid #0057a8;background:#e0f2fe;border-radius:9px;padding:8px 10px;margin-bottom:6px;cursor:pointer;font-size:13px}.dg62-event strong{font-size:14px}.dg62-event .who{color:#475569;margin-top:3px;font-size:12px}.dg62-share{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px;margin-top:8px}.dg62-share label{display:flex;gap:8px;align-items:center;margin:0;padding:9px;border:1px solid #d1d5db;border-radius:10px}.dg62-share input{width:auto}.dg62-modal{position:fixed;inset:0;z-index:14000;background:rgba(0,0,0,.48);display:flex;align-items:center;justify-content:center;padding:15px}.dg62-modal.hidden{display:none!important}.dg62-card{background:#fff;border-radius:18px;max-width:720px;width:100%;max-height:94vh;overflow:auto;padding:20px}.dg62-worker-row{display:grid;grid-template-columns:minmax(160px,1fr) minmax(240px,2fr) auto auto auto;gap:7px;align-items:center;padding:8px 0;border-top:1px solid #e5e7eb}.dg62-worker-row .btn{width:auto;padding:8px}.dg62-muted{font-size:12px;color:#64748b}@media(max-width:700px){.dg62-person{grid-template-columns:1fr}.dg62-personname{border-right:0}.dg62-worker-row{grid-template-columns:1fr}.dg62-toolbar{display:grid;grid-template-columns:1fr 1fr}.dg62-toolbar .btn{width:100%}}`;document.head.appendChild(s)}
function modal(){if($('dg62EventModal'))return;const m=document.createElement('div');m.id='dg62EventModal';m.className='dg62-modal hidden';m.innerHTML='<div class="dg62-card"><h2 id="dg62ModalTitle" style="margin-top:0">Termin anlegen</h2><label>Kundenname</label><input id="dg62Customer"><label>Adresse</label><input id="dg62Address"><label>Was ist zu tun</label><textarea id="dg62Task"></textarea><div class="grid2"><div><label>Datum</label><input id="dg62EventDate" type="date"></div><div></div></div><div class="grid2"><div><label>Von</label><input id="dg62Start" type="time"></div><div><label>Bis</label><input id="dg62End" type="time"></div></div><label>Termin teilen mit</label><div class="muted small">Haken setzen – der Termin erscheint bei allen ausgewählten Monteuren.</div><div id="dg62Share" class="dg62-share"></div><div id="dg62ModalStatus"></div><div class="button-row" style="margin-top:14px"><button class="btn success" onclick="dg62SaveEvent()">Termin speichern</button><button class="btn secondary" onclick="dg62CloseModal()">Abbrechen</button></div><button id="dg62DeleteBtn" class="btn danger hidden" style="width:100%;margin-top:8px" onclick="dg62DeleteEvent()">Termin löschen</button></div>';document.body.appendChild(m)}
function inject(){if($('dg62PlannerCard')||!$('bossView'))return;const c=document.createElement('div');c.className='card';c.id='dg62PlannerCard';c.innerHTML='<details class="dg62-main"><summary class="dg62-summary">Mitarbeiter Kalender</summary><div class="muted small">Montag bis Freitag · Mitarbeiter und Termine je Tag untereinander · Rot = geplante Zeit unter Soll · Grün = Soll erreicht oder überschritten.</div><div class="dg62-toolbar"><button class="btn success" onclick="dg62NewEvent()">+ Termin</button><button class="btn secondary" onclick="dg62ShiftWeek(-7)">← Vorwoche</button><button class="btn secondary" onclick="dg62Today()">Diese Woche</button><button class="btn secondary" onclick="dg62ShiftWeek(7)">Nächste Woche →</button><input id="dg62Date" type="date" onchange="dg62GoDate(this.value)"><button class="btn primary" onclick="dg62Load()">↻ Synchronisieren</button></div><div id="dg62Status"></div><div id="dg62WeekLabel" style="font-weight:800;margin:8px 0"></div><div id="dg62Week"></div><details style="margin-top:14px"><summary style="cursor:pointer;font-weight:800">Kalender-Mitarbeiter verwalten</summary><div class="muted small" style="margin:8px 0">Nur Monteure/Baustellenpersonal hier aktivieren. Reihenfolge kann jederzeit geändert werden.</div><div id="dg62Workers"></div><div class="admin-grid" style="margin-top:10px"><div><label>Mitarbeiter</label><input id="dg62NewWorkerName" placeholder="Name"></div><div><label>Google Kalender-ID</label><input id="dg62NewWorkerCal" placeholder="Kalender-ID"></div></div><button class="btn success" style="width:100%;margin-top:8px" onclick="dg62AddWorker()">+ Mitarbeiter hinzufügen</button><div id="dg62WorkerStatus"></div></details></details>';$('bossView').insertBefore(c,$('bossView').firstChild);modal();c.querySelector('.dg62-main').addEventListener('toggle',function(){if(this.open&&!workers.length)dg62Load()})}
function renderWorkers(){const b=$('dg62Workers');if(!b)return;b.innerHTML=workers.map((w,i)=>'<div class="dg62-worker-row"><strong>'+esc(w.displayName||w.employeeName)+'</strong><span class="dg62-muted">'+esc(w.calendarId||'Keine Kalender-ID')+'</span><button class="btn secondary" '+(i?'':'disabled')+' onclick="dg62MoveWorker(\''+esc(w.id)+'\',-1)">↑</button><button class="btn secondary" '+(i===workers.length-1?'disabled':'')+' onclick="dg62MoveWorker(\''+esc(w.id)+'\',1)">↓</button><button class="btn '+(w.active?'danger':'success')+'" onclick="dg62ToggleWorker(\''+esc(w.id)+'\','+(!w.active)+')">'+(w.active?'Entfernen':'Aktivieren')+'</button></div>').join('')||'<div class="muted">Noch keine Kalender-Mitarbeiter vorhanden.</div>'}
function renderEvent(e){return '<div class="dg62-event" '+(e.external?'style="border-left-color:#64748b;background:#f1f5f9;cursor:default"':'onclick="event.stopPropagation();dg62EditEvent(\''+esc(e.id)+'\')"')+'><strong>'+esc(e.start)+'–'+esc(e.end)+' · '+esc(e.customer)+'</strong><br>'+esc(e.address||'')+'<br>'+esc(e.task||'')+'<div class="who">'+(e.employeeNames||[]).map(esc).join(' · ')+(e.external?' · Google-Termin':'')+'</div></div>'}
function renderWeek(){const ws=workers.filter(w=>w.active),ds=Array.from({length:5},(_,i)=>add(weekStart,i));$('dg62WeekLabel').textContent=fmtDate(ds[0])+' – '+fmtDate(ds[4]);$('dg62Week').innerHTML=ds.map((d,di)=>'<section class="dg62-day"><div class="dg62-dayhead">'+fmtDate(d)+'</div>'+ws.map(w=>{const es=events.filter(e=>e.date===d&&Array.isArray(e.employeeIds)&&e.employeeIds.includes(w.id)).sort((a,b)=>(a.start||'').localeCompare(b.start||''));const planned=es.reduce((s,e)=>s+eventHours(e),0),target=targetHours(w.displayName||w.employeeName,di),cls=es.length?(planned+1e-6<target?' dg62-under':' dg62-ok'):'';return '<div class="dg62-person'+cls+'"><div class="dg62-personname">'+esc(w.displayName||w.employeeName)+(es.length?'<div class="dg62-hours">Geplant: '+fmtH(planned)+' Std. / Soll: '+fmtH(target)+' Std.</div>':'')+'</div><div class="dg62-events" onclick="if(event.target===this||event.target.classList.contains(\'dg62-empty\'))dg62NewEvent(\''+d+'\',\''+esc(w.id)+'\')">'+(es.length?es.map(renderEvent).join(''):'<div class="dg62-empty">+ Termin eintragen</div>')+'</div></div>'}).join('')+'</section>').join('')}
window.dg62Load=async function(){if(!navigator.onLine){setSt('dg62Status','Offline – Kalender kann nicht synchronisiert werden.','warn');return}try{setSt('dg62Status','Kalender wird synchronisiert …','info');const end=add(weekStart,4);const result=await Promise.all([api(chefPayload({action:'getPlannerWorkers'})),api(chefPayload({action:'getPlannerEvents',startDate:weekStart,endDate:end})),api(chefPayload({action:'getEmployeeAdminData'}))]);workers=result[0]||[];events=result[1]||[];adminRows=result[2]||[];renderWorkers();renderWeek();setSt('dg62Status','✓ Kalender synchronisiert.','ok')}catch(e){setSt('dg62Status',e&&e.message?e.message:'Kalender konnte nicht geladen werden.','error')}};
window.dg62Today=function(){weekStart=monday();$('dg62Date').value=weekStart;dg62Load()};window.dg62ShiftWeek=function(n){weekStart=add(weekStart,n);$('dg62Date').value=weekStart;dg62Load()};window.dg62GoDate=function(v){weekStart=monday(v);dg62Load()};
function shareHtml(selected=[]){return workers.filter(w=>w.active).map(w=>'<label><input type="checkbox" class="dg62-share-cb" value="'+esc(w.id)+'" '+(selected.includes(w.id)?'checked':'')+'>'+esc(w.displayName||w.employeeName)+'</label>').join('')}
window.dg62NewEvent=function(d,w){editId='';$('dg62ModalTitle').textContent='Termin anlegen';$('dg62Customer').value='';$('dg62Address').value='';$('dg62Task').value='';$('dg62EventDate').value=d||iso(new Date());$('dg62Start').value='08:00';$('dg62End').value='09:00';$('dg62Share').innerHTML=shareHtml(w?[w]:[]);$('dg62DeleteBtn').classList.add('hidden');$('dg62EventModal').classList.remove('hidden')};
window.dg62EditEvent=function(id){const e=events.find(x=>x.id===id);if(!e||e.external)return;editId=id;$('dg62ModalTitle').textContent='Termin bearbeiten';$('dg62Customer').value=e.customer||'';$('dg62Address').value=e.address||'';$('dg62Task').value=e.task||'';$('dg62EventDate').value=e.date||'';$('dg62Start').value=e.start||'';$('dg62End').value=e.end||'';$('dg62Share').innerHTML=shareHtml(e.employeeIds||[]);$('dg62DeleteBtn').classList.remove('hidden');$('dg62EventModal').classList.remove('hidden')};
window.dg62CloseModal=function(){$('dg62EventModal').classList.add('hidden')};
window.dg62SaveEvent=async function(){const customer=$('dg62Customer').value.trim(),address=$('dg62Address').value.trim(),task=$('dg62Task').value.trim(),date=$('dg62EventDate').value,start=$('dg62Start').value,end=$('dg62End').value,employeeIds=[...document.querySelectorAll('.dg62-share-cb:checked')].map(x=>x.value);if(!customer||!address||!task||!date||!start||!end){setSt('dg62ModalStatus','Bitte Kundenname, Adresse, Tätigkeit, Datum und Zeit vollständig eintragen.','error');return}if(!employeeIds.length){setSt('dg62ModalStatus','Bitte mindestens einen Monteur auswählen.','error');return}try{setSt('dg62ModalStatus','Termin wird gespeichert und synchronisiert …','info');await api(chefPayload({action:'savePlannerEvent',item:{id:editId,customer,address,task,date,start,end,employeeIds}}));dg62CloseModal();weekStart=monday(date);$('dg62Date').value=weekStart;await dg62Load()}catch(e){setSt('dg62ModalStatus',e&&e.message?e.message:'Termin konnte nicht gespeichert werden.','error')}};
window.dg62DeleteEvent=async function(){if(!editId||!confirm('Termin wirklich löschen? Er wird auch aus den zugeordneten Google-Kalendern entfernt.'))return;try{setSt('dg62ModalStatus','Termin wird gelöscht …','info');await api(chefPayload({action:'deletePlannerEvent',id:editId}));dg62CloseModal();await dg62Load()}catch(e){setSt('dg62ModalStatus',e&&e.message?e.message:'Termin konnte nicht gelöscht werden.','error')}};
window.dg62MoveWorker=async function(id,direction){try{await api(chefPayload({action:'movePlannerWorker',id,direction}));await dg62Load()}catch(e){setSt('dg62WorkerStatus',e.message,'error')}};
window.dg62ToggleWorker=async function(id,active){try{await api(chefPayload({action:'setPlannerWorkerActive',id,active}));await dg62Load()}catch(e){setSt('dg62WorkerStatus',e.message,'error')}};
window.dg62AddWorker=async function(){const name=$('dg62NewWorkerName').value.trim(),calendarId=$('dg62NewWorkerCal').value.trim();if(!name||!calendarId){setSt('dg62WorkerStatus','Bitte Mitarbeitername und Google Kalender-ID eintragen.','error');return}try{setSt('dg62WorkerStatus','Kalender-ID wird geprüft und Mitarbeiter angelegt …','info');await api(chefPayload({action:'savePlannerWorker',item:{displayName:name,employeeName:name,provider:'google',calendarId,active:true}}));$('dg62NewWorkerName').value='';$('dg62NewWorkerCal').value='';await dg62Load();setSt('dg62WorkerStatus','✓ Kalender-Mitarbeiter hinzugefügt.','ok')}catch(e){setSt('dg62WorkerStatus',e.message,'error')}};
const oldShowBoss=window.showBoss;if(typeof oldShowBoss==='function')window.showBoss=function(){const r=oldShowBoss.apply(this,arguments);setTimeout(()=>{inject();closeRegie();if(!weekStart){weekStart=monday();if($('dg62Date'))$('dg62Date').value=weekStart}removeLegacyWarnings()},120);return r};
css();inject();closeRegie();removeLegacyWarnings();const mo=new MutationObserver(removeLegacyWarnings);mo.observe(document.documentElement,{subtree:true,childList:true});document.title='DG Zeiterfassung v62';const lv=document.querySelector('.login-card .center.muted.small');if(lv)lv.textContent='Version 62';const hv=document.querySelector('.hero .head-row strong');if(hv)hv.textContent='Zeiterfassung · v62';
})();