(function(){
'use strict';
if(window.__DG_V62_OFFERS__)return;window.__DG_V62_OFFERS__=true;
const $=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addCss(){if($('dg62OfferCss'))return;const s=document.createElement('style');s.id='dg62OfferCss';s.textContent=`.dg62-offer-card{border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin-top:10px;background:#fff}.dg62-offer-card.create{border-left:5px solid #d97706}.dg62-offer-card.open{border-left:5px solid #2563eb}.dg62-offer-card.accepted{border-left:5px solid #166534}.dg62-offer-card.declined{border-left:5px solid #b91c1c}.dg62-offer-meta{font-size:13px;color:var(--muted);margin-top:5px}.dg62-offer-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.dg62-offer-actions .btn{width:auto}.dg62-offer-badge{display:inline-block;padding:4px 8px;border-radius:999px;font-size:12px;font-weight:800}.dg62-offer-badge.create{background:#ffedd5;color:#9a3412}.dg62-offer-badge.open{background:#dbeafe;color:#1d4ed8}.dg62-offer-badge.accepted{background:#dcfce7;color:#166534}.dg62-offer-badge.declined{background:#fee2e2;color:#991b1b}@media(max-width:700px){.dg62-offer-actions{display:grid;grid-template-columns:1fr}.dg62-offer-actions .btn{width:100%}}`;document.head.appendChild(s)}
function findRegieCard(){const root=$('bossView');if(!root)return null;return [...root.querySelectorAll(':scope > .card')].find(c=>{const h=c.querySelector('.dg48-head h2,:scope > h2');return h&&String(h.textContent||'').trim()==='Regieberichte'})||null}
function makeSection(id,title,stage){if($(id))return $(id);const regie=findRegieCard(),root=$('bossView');if(!root)return null;const c=document.createElement('div');c.className='card';c.id=id;c.innerHTML='<div class="dg48-head"><h2>'+esc(title)+'</h2><button type="button" class="dg48-toggle">+</button></div><div class="dg48-body hidden"><div class="muted small">'+(stage==='Zu erstellen'?'Besichtigungstermine, für die noch ein Angebot erstellt werden muss.':stage==='Offen'?'Erstellte Angebote, bei denen die Kundenentscheidung noch aussteht.':'Abgeschlossene Angebotsentscheidungen.')+'</div><div id="'+id+'Status"></div><div id="'+id+'List"></div></div>';const head=c.querySelector('.dg48-head'),body=c.querySelector('.dg48-body'),btn=c.querySelector('.dg48-toggle');head.addEventListener('click',async()=>{const open=body.classList.contains('hidden');body.classList.toggle('hidden',!open);btn.textContent=open?'−':'+';if(open)await loadOffers(stage)});if(regie)regie.insertAdjacentElement('afterend',c);else root.prepend(c);return c}
function ensureSections(){addCss();makeSection('dg62OfferCreate','Angebote zu erstellen','Zu erstellen');makeSection('dg62OfferOpen','Offene Angebote','Offen');makeSection('dg62OfferArchive','Angebotsarchiv','Archiv')}
function sectionIds(stage){return stage==='Zu erstellen'?['dg62OfferCreateStatus','dg62OfferCreateList']:stage==='Offen'?['dg62OfferOpenStatus','dg62OfferOpenList']:['dg62OfferArchiveStatus','dg62OfferArchiveList']}
function reportHtml(r){const links=typeof reportLinks==='function'?reportLinks(r):'';return '<div class="entry"><strong>'+esc(typeof formatDateDE==='function'?formatDateDE(r.date):r.date)+' · '+esc(r.employee)+' · '+esc(typeof formatHours==='function'?formatHours(r.hours||0):r.hours)+' Std.</strong><div class="dg62-offer-meta">'+esc(r.start||'')+'–'+esc(r.end||'')+'</div><div>'+esc(r.activity||'')+'</div>'+(r.materialUsed?'<div class="dg62-offer-meta"><strong>Material:</strong> '+esc(r.material||'')+'</div>':'')+(links?'<div class="report-actions">'+links+'</div>':'')+'</div>'}
function renderOfferCard(g,stage){const range=g.firstDate===g.lastDate?(typeof formatDateDE==='function'?formatDateDE(g.firstDate):g.firstDate):((typeof formatDateDE==='function'?formatDateDE(g.firstDate):g.firstDate)+' bis '+(typeof formatDateDE==='function'?formatDateDE(g.lastDate):g.lastDate));let cls='create',badge='🟠 Angebot zu erstellen',actions='';if(stage==='Offen'){cls='open';badge='🔵 Offenes Angebot';actions='<button class="btn success" onclick="dg62OfferDecision(\''+esc(g.offerId)+'\',\'Angebot Angenommen\')">Angenommen</button><button class="btn danger" onclick="dg62OfferDecision(\''+esc(g.offerId)+'\',\'Angebot Abgelehnt\')">Abgelehnt</button>'}else if(stage==='Zu erstellen'){actions='<button class="btn success" onclick="dg62OfferCreated(\''+esc(g.offerId)+'\')">Angebot erstellt</button><button class="btn danger" onclick="dg62DiscardOffer(\''+esc(g.offerId)+'\')">Auftrag löschen</button>'}else if(g.status==='Angebot Angenommen'){cls='accepted';badge='🟢 Angenommen'}else{cls='declined';badge='🔴 Abgelehnt'}const reports=(g.reports||[]).map(reportHtml).join('');return '<div class="dg62-offer-card '+cls+'"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><strong>🏢 '+esc(g.customer||'Objekt')+'</strong><span class="dg62-offer-badge '+cls+'">'+badge+'</span></div><div class="dg62-offer-meta">'+esc(range)+' · '+Number(g.reportCount||0)+' Bericht(e) · '+esc(typeof formatHours==='function'?formatHours(g.totalHours||0):g.totalHours)+' Std.</div><div class="dg62-offer-meta"><strong>Mitarbeiter:</strong> '+esc((g.employees||[]).join(', ')||'–')+'</div><details style="margin-top:10px"><summary>Einzelberichte anzeigen</summary>'+reports+'</details>'+(actions?'<div class="dg62-offer-actions">'+actions+'</div>':'')+(g.changedAt?'<div class="dg62-offer-meta">Letzte Änderung: '+esc(g.changedAt)+(g.changedBy?' · '+esc(g.changedBy):'')+'</div>':'')+'</div>'}
window.loadOffers=async function(stage){ensureSections();const ids=sectionIds(stage),st=$(ids[0]),out=$(ids[1]);if(!st||!out)return;if(!navigator.onLine){st.className='status warn';st.textContent='Angebote benötigen Internet.';return}try{st.className='status info';st.textContent='Angebote werden geladen …';const rows=await api(chefPayload({action:'getOfferReports',stage}));out.innerHTML=(rows||[]).map(g=>renderOfferCard(g,stage)).join('')||'<div class="status ok">Keine Einträge vorhanden.</div>';st.className='status ok';st.textContent=(rows||[]).length+' Vorgang/Vorgänge geladen.'}catch(e){st.className='status error';st.textContent=e&&e.message?e.message:'Angebote konnten nicht geladen werden.'}}
function refreshOfferIfOpen(stage){const id=stage==='Zu erstellen'?'dg62OfferCreate':stage==='Offen'?'dg62OfferOpen':'dg62OfferArchive',c=$(id),b=c&&c.querySelector('.dg48-body');if(b&&!b.classList.contains('hidden'))loadOffers(stage)}
window.dg62MoveToOffer=async function(encoded){let ids=[];try{ids=JSON.parse(decodeURIComponent(encoded))}catch(_e){}if(!ids.length)return;if(!confirm('Diesen Besichtigungs-/Kundentermin in „Angebote zu erstellen“ verschieben? Er wird danach nicht mehr als abzurechnender Regiebericht geführt.'))return;try{setMessage('regieStatus','Vorgang wird zu „Angebote zu erstellen“ verschoben …','info');await api(chefPayload({action:'setRegieReportsOfferStatus',entryIds:ids,offerStatus:'Angebot zu erstellen'}));setMessage('regieStatus','✅ Vorgang wurde zu „Angebote zu erstellen“ verschoben.','ok');const view=window.__regieStatus||'Abgeschlossen';await loadRegieReports(view);refreshOfferIfOpen('Zu erstellen')}catch(e){setMessage('regieStatus','Verschieben nicht möglich: '+(e&&e.message?e.message:e),'error')}};
window.dg62OfferCreated=async function(offerId){if(!confirm('Angebot wurde erstellt und soll jetzt unter „Offene Angebote“ auf die Kundenentscheidung warten?'))return;try{await api(chefPayload({action:'setRegieReportsOfferStatus',offerId,offerStatus:'Offenes Angebot'}));await loadOffers('Zu erstellen');refreshOfferIfOpen('Offen')}catch(e){alert(e.message||e)}};
window.dg62OfferDecision=async function(offerId,statusName){const accepted=statusName==='Angebot Angenommen';if(!confirm('Angebot wirklich als „'+(accepted?'Angenommen':'Abgelehnt')+'“ bestätigen und archivieren?'))return;try{await api(chefPayload({action:'setRegieReportsOfferStatus',offerId,offerStatus:statusName}));await loadOffers('Offen');refreshOfferIfOpen('Archiv')}catch(e){alert(e.message||e)}};
window.dg62DiscardOffer=async function(offerId){if(!confirm('Auftrag wirklich endgültig aus der Auftrags- und Angebotsverwaltung entfernen? Dieser Vorgang kann danach nicht wiederhergestellt werden.'))return;try{await api(chefPayload({action:'discardOfferPermanently',offerId}));await loadOffers('Zu erstellen')}catch(e){alert(e.message||e)}};
async function addOfferButtons(view){if(view!=='Abgeschlossen')return;let groups=[];try{if(Array.isArray(window.__dgRegieRaw)&&window.__dgRegieRaw.length)groups=window.__dgRegieRaw.slice();else groups=await api(chefPayload({action:'getRegieReports',status:'Offen',year:0,month:0}));if(typeof mergeRegieGroups==='function')groups=mergeRegieGroups(groups||[]);groups=(groups||[]).filter(g=>(g.jobStatus||'Abgeschlossen')==='Abgeschlossen')}catch(_e){return}const cards=[...document.querySelectorAll('#regieResult > .report-card')];cards.forEach((card,i)=>{const g=groups[i];if(!g||card.querySelector('.dg62-to-offer'))return;const entryIds=(g.reports||[]).map(r=>r.id).filter(Boolean);if(!entryIds.length)return;const actions=card.querySelector(':scope > .report-actions')||card.querySelector('.report-actions');if(!actions)return;const b=document.createElement('button');b.type='button';b.className='btn primary dg62-to-offer';b.textContent='→ Angebot zu erstellen';b.onclick=()=>dg62MoveToOffer(encodeURIComponent(JSON.stringify(entryIds)));actions.appendChild(b)})}
const oldLoad=window.loadRegieReports;if(typeof oldLoad==='function')window.loadRegieReports=async function(view){const r=await oldLoad.apply(this,arguments);await addOfferButtons(view);return r};
const oldSet=window.setRegieObjectJobStatus;if(typeof oldSet==='function')window.setRegieObjectJobStatus=async function(objectIds,jobStatus){const ids=String(objectIds||'').split(',').filter(Boolean);if(!ids.length){setMessage('regieStatus','Objekt-ID fehlt. Bitte Regieberichte neu laden.','error');return}const completed=jobStatus==='Abgeschlossen';const question=completed?'Diesen laufenden Auftrag wirklich als abgeschlossen markieren?':'Diesen Auftrag wirklich wieder auf „Laufend“ setzen? Damit wird eine falsche Abschlussmeldung korrigiert.';if(!confirm(question))return;const view=window.__regieStatus||(!completed?'Abgeschlossen':'Laufend');try{let count=0;for(const objectId of ids){const r=await api(chefPayload({action:'setRegieObjectJobStatus',objectId,jobStatus}));count+=Number(r.count||0)}setMessage('regieStatus',completed?'✅ Auftrag abgeschlossen.':'✅ Status korrigiert. '+count+' Regiebericht(e) sind wieder dem laufenden Auftrag zugeordnet.','ok');await loadRegieReports(view)}catch(e){setMessage('regieStatus','Statusänderung nicht möglich: '+e.message,'error')}};
const oldBoss=window.showBoss;if(typeof oldBoss==='function')window.showBoss=function(){const r=oldBoss.apply(this,arguments);setTimeout(ensureSections,120);return r};
ensureSections();
})();