function api(payload){return d3Api(payload);}
function setMessage(id,msg,type='info'){if(id==='regieStatus'&&DG3.active==='Laufend')id='d3RunningStatus';const e=$(id);if(e){e.className='status '+type;e.textContent=msg;}}
function clearMessage(id){if(id==='regieStatus'&&DG3.active==='Laufend')id='d3RunningStatus';const e=$(id);if(e){e.className='';e.textContent='';}}
function applyDayStatus(status){status=status||'Arbeiten';const blocked=status!=='Arbeiten'&&!canAccessBoss();$('workEntryCard').classList.toggle('hidden',blocked);$('dayCloseCard').classList.toggle('hidden',blocked);if(status!=='Arbeiten')setMessage('dayStatusMessage','Dieser Tag ist als '+status+' erfasst. Verwaltung durch das Buero.'+(lastDayData.creditedHours?' Gutschrift: '+formatHours(lastDayData.creditedHours)+' Std.':''),'info');else clearMessage('dayStatusMessage');}
function showBoss(){if(!canAccessBoss()){showEmployee();setMessage('entryStatus','Kein Zugriff auf Buero.','error');return;}$('employeeView').classList.add('hidden');$('bossView').classList.remove('hidden');$('employeeTab').classList.remove('active');$('bossTab').classList.add('active');if(navigator.onLine){d3CheckBackend();d3Dashboard();}}
async function loadDay(){const a=auth(),date=$('date').value;if(!a.employee||!date)return;const token=DG3.dayToken=(DG3.dayToken||0)+1,key='dg_day_'+a.employee+'_'+date;const current=()=>auth().employee===a.employee&&date===$('date').value&&token===DG3.dayToken;try{let data;if(!navigator.onLine){const cached=localStorage.getItem(key);data=cached?JSON.parse(cached):{entries:[],total:0,closed:false,status:'Arbeiten'};}else{data=await api({action:'getDayData',employee:a.employee,pin:a.pin,date});if(current())localStorage.setItem(key,JSON.stringify(data));}if(current()){lastDayData=data;renderDay();}}catch(e){if(current())setMessage('entryStatus',e.message,'error');}}
function loadRegieReports(view){return d3Reports(view||DG3.active);}
function requestMergeSelectedRegieReports(view){return d3Merge(view||DG3.active);}
function confirmMergeSelectedRegieReports(){return d3ConfirmMerge();}
function closeRegieMergeConfirm(){DG3.merge=null;$('regieMergeConfirmModal').classList.add('hidden');}
function updateRegieMergeButton(view){const root=d3ReportRoot(view||DG3.active),n=root.querySelectorAll('.regie-merge-select:checked').length,h=root.querySelector('.d3-hint');if(h)h.textContent=n+' Kundenkarte(n) markiert.';}
function setRegieObjectJobStatus(ids,status){return d3JobStatus(ids,status);}
function markRegieObjectBilled(ids){return d3Bill(ids);}
async function queueAll(){const db=await openDb(),all=await new Promise((res,rej)=>{const r=db.transaction('queue','readonly').objectStore('queue').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});db.close();return all.filter(x=>(x.owner||x.payload?.employee||x.payload?.entry?.employee)===auth().employee);}
async function queuePut(item){item=JSON.parse(JSON.stringify(item));item.owner=item.owner||item.payload?.employee||item.payload?.entry?.employee||auth().employee;if(item.payload){delete item.payload.pin;delete item.payload.employeePin;if(item.payload.entry)delete item.payload.entry.employeePin;}const db=await openDb();await new Promise((res,rej)=>{const t=db.transaction('queue','readwrite');t.objectStore('queue').put(item);t.oncomplete=res;t.onerror=()=>rej(t.error);});db.close();}
async function syncQueue(show){if(DG3.queueBusy||!navigator.onLine)return;const a=auth();if(!a.employee||!a.pin)return;DG3.queueBusy=true;let sent=0,failed=0;const blocked=new Set();try{for(const item of (await queueAll()).sort((a,b)=>a.createdAt-b.createdAt)){if(auth().employee!==a.employee)break;const date=queuedItemInfo(item).date;if((item.type==='closeDay'&&blocked.has(date))||(item.error&&!show)){blocked.add(date);failed++;continue;}try{const payload={...item.payload,employee:a.employee,pin:a.pin,employeePin:a.pin};if(payload.entry)payload.entry={...payload.entry,employeePin:a.pin};await api(payload);await queueDelete(item.id);sent++;}catch(e){failed++;blocked.add(date);if(['network','version'].includes(e.dgType))break;item.error=e.message;await queuePut(item);}}await refreshQueueCount();if(sent)await loadDay();if(show)setMessage('entryStatus',sent+' uebertragen, '+failed+' noch offen. Details pruefen.',failed?'warn':'ok');}finally{DG3.queueBusy=false;}}
async function retryQueueItem(id){const item=(await queueAll()).find(x=>Number(x.id)===Number(id));if(!item)return;delete item.error;await queuePut(item);await syncQueue(true);}
async function renderQueueDetails(){const box=$('queueDetails');if(!box)return;box.innerHTML=(await queueAll()).map(item=>{const x=queuedItemInfo(item);return '<div class="entry"><strong>'+esc(x.title)+'</strong><div>'+esc(x.date)+' '+esc(x.time)+'</div>'+(item.error?'<div class="status error">'+esc(item.error)+'</div>':'')+'<div class="report-actions">'+d3Button('Erneut uebertragen','retryQueueItem',[item.id])+ (item.type==='saveEntry'?d3Button('Korrigieren','d3EditQueue',[item.id],'secondary'):'')+'</div></div>';}).join('')||'Keine ausstehenden Uebertragungen.';}
