}
function d37PlannerConflicts(){const ids=d37SelectedWorkerIds(),date=val('dg62ED'),start=val('dg62Start'),end=val('dg62End');if(date!==S.previewDate)return [];return (S.previewEvents||[]).filter(e=>String(e.id)!==String(S.plannerEditId||'')&&(e.employeeIds||[]).some(id=>ids.includes(String(id)))&&d37Overlap(e,start,end));}
const baseNew37=window.dg62New;
if(typeof baseNew37==='function')window.dg62New=function(){S.plannerEditId='';S.pendingWorkerIds=[];S.plannerLink=null;const r=baseNew37.apply(this,arguments);setTimeout(d37RepairPlannerAssignment,0);return r;};
const baseEdit37=window.dg62Edit;
if(typeof baseEdit37==='function')window.dg62Edit=function(id){S.plannerEditId=String(id||'');const r=baseEdit37.apply(this,arguments);setTimeout(d37RepairPlannerAssignment,0);return r;};
const baseSave37=window.dg62Save;
if(typeof baseSave37==='function')window.dg62Save=async function(){const conflicts=d37PlannerConflicts();if(conflicts.length&&!confirm('Achtung: Der gewählte Zeitraum überschneidet sich mit '+conflicts.length+' vorhandenem Termin(en) des ausgewählten Mitarbeiters. Trotzdem speichern?'))return;return baseSave37.apply(this,arguments);};
const baseApi37=window.api;
if(typeof baseApi37==='function')window.api=api=async function(payload){
  if(payload&&payload.action==='savePlannerEvent'&&payload.item&&payload.item.type==='Wartung'&&S.plannerLink){Object.assign(payload.item,{maintenanceCustomerId:S.plannerLink.customerId||'',maintenanceObjectId:S.plannerLink.objectId||'',maintenanceDeviceId:S.plannerLink.deviceId||''});}
  const r=await baseApi37.apply(this,arguments);
  if(payload&&payload.action==='savePlannerEvent')S.plannerLink=null;
  return r;
};

/* ---------- Wartungskunden: Formular ---------- */
function d37BlankCustomer(){return{id:'',name:'',billingStreet:'',billingZip:'',billingCity:'',email:'',phone:'',objects:[d37BlankObject()]};}
function d37BlankObject(){return{id:'',name:'',street:'',zip:'',city:'',notes:'',devices:[d37BlankDevice()]};}
function d37BlankDevice(){return{id:'',deviceType:'Gas Brennwert',otherDescription:'',manufacturer:'',model:'',serialNumber:'',year:'',tenantName:'',tenantPhone:'',tenantEmail:'',sparePartManufacturer:'',sparePartSerialNumber:'',internalNotes:'',nextMaintenanceDue:'',repairs:[]};}
function d37Field(label,key,value='',type='text',extra=''){return '<label>'+label+'</label><input data-d37="'+key+'" type="'+type+'" value="'+esc37(value)+'" '+extra+'>';}
function d37DeviceHtml(d,oi,di){
  const repairs=(d.repairs||[]).map(r=>'<div class="d37-repair"><b>'+esc37(formatDateDE(r.date||''))+'</b> · '+esc37(r.description||'')+(r.createdBy?'<div class="small muted">Erfasst von '+esc37(r.createdBy)+'</div>':'')+'</div>').join('');
  const history=(d.history||[]).map(r=>'<div class="d37-repair"><b>'+esc37(formatDateDE(r.date||''))+'</b> · '+esc37(r.description||'')+'<div class="small muted">'+esc37(r.employee||'')+' · '+Number(r.hours||0).toFixed(2).replace('.',',')+' Std.'+(r.nextMaintenanceDue?' · nächste Wartung '+esc37(monthLabel(r.nextMaintenanceDue)):'')+'</div></div>').join('');
  return '<div class="d37-device" data-device-index="'+di+'" data-device-id="'+esc37(d.id||'')+'"><div class="d37-subhead"><strong>Gerät '+(di+1)+'</strong><button type="button" class="btn danger d37-mini" onclick="return d37RemoveDevice('+oi+','+di+')">Gerät entfernen</button></div><div class="d37-grid3">'
    +'<div><label>Geräteart</label><select data-d37="deviceType" onchange="d37ToggleOther(this)">'+['Gas Atmosphärisch','Gas Brennwert','Öl Atmosphärisch','Öl Brennwert','Hebeanlage','Sonstiges'].map(x=>'<option '+(d.deviceType===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div>'
    +'<div class="d37-other '+(d.deviceType==='Sonstiges'?'':'hidden')+'">'+d37Field('Beschreibung bei Sonstiges','otherDescription',d.otherDescription)+'</div>'
    +'<div>'+d37Field('Hersteller','manufacturer',d.manufacturer)+'</div><div>'+d37Field('Typ / Modell','model',d.model)+'</div><div>'+d37Field('Seriennummer','serialNumber',d.serialNumber)+'</div><div>'+d37Field('Baujahr','year',d.year,'number','min="1900" max="2200"')+'</div>'
    +'<div>'+d37Field('Ersatzteil-Hersteller','sparePartManufacturer',d.sparePartManufacturer)+'</div><div>'+d37Field('Ersatzteil-Seriennummer','sparePartSerialNumber',d.sparePartSerialNumber)+'</div><div>'+d37Field('Nächste Wartung fällig','nextMaintenanceDue',d.nextMaintenanceDue,'month')+'</div></div>'
    +'<div class="d37-section-label">Mieter / Ansprechpartner am Gerät <span class="muted small">(optional)</span></div><div class="d37-grid3"><div>'+d37Field('Name','tenantName',d.tenantName)+'</div><div>'+d37Field('Telefon','tenantPhone',d.tenantPhone,'tel')+'</div><div>'+d37Field('E-Mail','tenantEmail',d.tenantEmail,'email')+'</div></div>'
    +'<label>Interne Vermerke</label><textarea data-d37="internalNotes">'+esc37(d.internalNotes||'')+'</textarea>'
    +(d.id?'<div class="d37-repair-box"><div class="d37-subhead"><strong>Wartungsberichte</strong></div>'+(history||'<div class="muted small">Noch keine abgeschlossenen Wartungen hinterlegt.</div>')+'<div class="d37-subhead" style="margin-top:12px"><strong>Reparaturen außerhalb des Wartungsvertrags</strong><button type="button" class="btn secondary d37-mini" onclick="return d37AddRepair(\''+esc37(d.id)+'\')">+ Reparatur eintragen</button></div>'+(repairs||'<div class="muted small">Noch keine Reparaturen hinterlegt.</div>')+'</div>':'')
    +'</div>';
}
function d37ObjectHtml(o,oi){return '<div class="d37-object" data-object-index="'+oi+'" data-object-id="'+esc37(o.id||'')+'"><div class="d37-subhead"><h3>Objekt '+(oi+1)+'</h3><button type="button" class="btn danger d37-mini" onclick="return d37RemoveObject('+oi+')">Objekt entfernen</button></div><div class="d37-grid2"><div>'+d37Field('Objektbezeichnung','objectName',o.name)+'</div><div>'+d37Field('Straße / Hausnummer','street',o.street)+'</div><div>'+d37Field('PLZ','zip',o.zip)+'</div><div>'+d37Field('Ort','city',o.city)+'</div></div><label>Objekt-Vermerk</label><textarea data-d37="objectNotes">'+esc37(o.notes||'')+'</textarea><div class="d37-devices">'+(o.devices||[]).map((d,di)=>d37DeviceHtml(d,oi,di)).join('')+'</div><button type="button" class="btn secondary" onclick="return d37AddDevice('+oi+')">+ Weiteres Gerät an diesem Objekt</button></div>';}
function d37RenderCustomerForm(hostId,model,mode){
  const host=$(hostId);if(!host)return;S.customer=JSON.parse(JSON.stringify(model||d37BlankCustomer()));
  host.innerHTML='<div class="d37-customer-form" data-host="'+esc37(hostId)+'" data-mode="'+esc37(mode)+'"><input type="hidden" class="d37CustomerId" value="'+esc37(S.customer.id||'')+'"><div class="d37-section-label">1. Kundendaten / Rechnungsempfänger</div><div class="d37-grid2"><div>'+d37Field('Name / Firma','customerName',S.customer.name)+'</div><div>'+d37Field('E-Mail','customerEmail',S.customer.email,'email')+'</div><div>'+d37Field('Telefon','customerPhone',S.customer.phone,'tel')+'</div><div>'+d37Field('Rechnungsadresse – Straße / Hausnummer','billingStreet',S.customer.billingStreet)+'</div><div>'+d37Field('Rechnungsadresse – PLZ','billingZip',S.customer.billingZip)+'</div><div>'+d37Field('Rechnungsadresse – Ort','billingCity',S.customer.billingCity)+'</div></div><div class="d37-section-label">2. Ausführungsorte / Objekte</div><div id="d37Objects">'+(S.customer.objects||[]).map(d37ObjectHtml).join('')+'</div><button type="button" class="btn secondary" onclick="return d37AddObject()">+ Weiteres Objekt hinzufügen</button><div class="d37CustomerStatus"></div><button type="button" class="btn success d37-save-customer" onclick="return d37SaveCustomer(\''+mode+'\')">'+(mode==='edit'?'Kundendaten speichern':'Kunde und Wartungsgeräte anlegen')+'</button></div>';
}
function d37ReadField(root,key){const e=root.querySelector('[data-d37="'+key+'"]');return e?String(e.value||'').trim():'';}
function d37ActiveCustomerForm(){return document.querySelector('#d37MaintenanceManage:not(.hidden) .d37-customer-form')||document.querySelector('#d37MaintenanceCreate:not(.hidden) .d37-customer-form')||document.querySelector('.d37-customer-form');}
function d37CollectCustomer(validate=true,root){
  root=root||d37ActiveCustomerForm();if(!root)return null;
  const c={id:String(root.querySelector('.d37CustomerId')?.value||'').trim(),name:d37ReadField(root,'customerName'),email:d37ReadField(root,'customerEmail'),phone:d37ReadField(root,'customerPhone'),billingStreet:d37ReadField(root,'billingStreet'),billingZip:d37ReadField(root,'billingZip'),billingCity:d37ReadField(root,'billingCity'),objects:[]};
  [...root.querySelectorAll('.d37-object')].forEach(or=>{const o={id:or.dataset.objectId||'',name:d37ReadField(or,'objectName'),street:d37ReadField(or,'street'),zip:d37ReadField(or,'zip'),city:d37ReadField(or,'city'),notes:d37ReadField(or,'objectNotes'),devices:[]};[...or.querySelectorAll(':scope > .d37-devices > .d37-device')].forEach(dr=>{const d={id:dr.dataset.deviceId||'',deviceType:d37ReadField(dr,'deviceType'),otherDescription:d37ReadField(dr,'otherDescription'),manufacturer:d37ReadField(dr,'manufacturer'),model:d37ReadField(dr,'model'),serialNumber:d37ReadField(dr,'serialNumber'),year:d37ReadField(dr,'year'),tenantName:d37ReadField(dr,'tenantName'),tenantPhone:d37ReadField(dr,'tenantPhone'),tenantEmail:d37ReadField(dr,'tenantEmail'),sparePartManufacturer:d37ReadField(dr,'sparePartManufacturer'),sparePartSerialNumber:d37ReadField(dr,'sparePartSerialNumber'),internalNotes:d37ReadField(dr,'internalNotes'),nextMaintenanceDue:d37ReadField(dr,'nextMaintenanceDue')};o.devices.push(d);});c.objects.push(o);});
  if(validate){
    if(!c.name||!c.billingStreet||!c.billingZip||!c.billingCity)throw new Error('Bitte Name und vollständige Rechnungsadresse eintragen.');
    if(!c.objects.length)throw new Error('Mindestens ein Ausführungsobjekt ist erforderlich.');
    c.objects.forEach((o,oi)=>{if(!o.name||!o.street||!o.zip||!o.city)throw new Error('Objekt '+(oi+1)+': Bezeichnung und vollständige Adresse fehlen.');if(!o.devices.length)throw new Error('Objekt '+(oi+1)+': Mindestens ein Wartungsgerät anlegen.');o.devices.forEach((d,di)=>{if(!d.deviceType)throw new Error('Objekt '+(oi+1)+', Gerät '+(di+1)+': Geräteart fehlt.');if(d.deviceType==='Sonstiges'&&!d.otherDescription)throw new Error('Objekt '+(oi+1)+', Gerät '+(di+1)+': Bei „Sonstiges“ ist die Beschreibung Pflicht.');if(!/^\d{4}-\d{2}$/.test(d.nextMaintenanceDue||''))throw new Error('Objekt '+(oi+1)+', Gerät '+(di+1)+': Nächste Wartung mit Monat und Jahr eintragen.');});});
  }
