  return c;
}
function d37SyncModel(){try{S.customer=d37CollectCustomer(false)||S.customer;}catch(_e){}return S.customer;}
window.d37ToggleOther=function(sel){const dev=sel.closest('.d37-device'),other=dev?.querySelector('.d37-other');if(other)other.classList.toggle('hidden',sel.value!=='Sonstiges');};
window.d37AddObject=function(){const form=d37ActiveCustomerForm(),c=d37SyncModel();c.objects=c.objects||[];c.objects.push(d37BlankObject());d37RenderCustomerForm(form?.dataset.host||'d37CustomerCreateHost',c,form?.dataset.mode||'create');return false;};
window.d37RemoveObject=function(i){const form=d37ActiveCustomerForm(),c=d37SyncModel();if(c.objects.length<=1)return alert('Mindestens ein Objekt muss vorhanden bleiben.');c.objects.splice(i,1);d37RenderCustomerForm(form?.dataset.host||'d37CustomerCreateHost',c,form?.dataset.mode||'create');return false;};
window.d37AddDevice=function(i){const form=d37ActiveCustomerForm(),c=d37SyncModel();c.objects[i].devices.push(d37BlankDevice());d37RenderCustomerForm(form?.dataset.host||'d37CustomerCreateHost',c,form?.dataset.mode||'create');return false;};
window.d37RemoveDevice=function(oi,di){const form=d37ActiveCustomerForm(),c=d37SyncModel();if(c.objects[oi].devices.length<=1)return alert('Mindestens ein Gerät muss an diesem Objekt vorhanden bleiben.');c.objects[oi].devices.splice(di,1);d37RenderCustomerForm(form?.dataset.host||'d37CustomerCreateHost',c,form?.dataset.mode||'create');return false;};
window.d37SaveCustomer=async function(mode){const form=d37ActiveCustomerForm(),st=form?.querySelector('.d37CustomerStatus');try{const item=d37CollectCustomer(true,form);if(st){st.className='d37CustomerStatus status info';st.textContent='Kundendaten werden gespeichert …';}const saved=await api(chefPayload({action:'saveMaintenanceCustomer',item}));S.customer=saved;d37RenderCustomerForm(mode==='edit'?'d37CustomerEditHost':'d37CustomerCreateHost',saved,'edit');const fresh=d37ActiveCustomerForm()?.querySelector('.d37CustomerStatus');if(fresh){fresh.className='d37CustomerStatus status ok';fresh.textContent='✓ Kunde, Objekte und Geräte gespeichert.';}await d37LoadMaintenanceOverview();}catch(e){if(st){st.className='d37CustomerStatus status error';st.textContent=e.message;}else d37Notice(e.message,'error');}return false;};
window.d37AddRepair=function(deviceId){if(typeof d3Form!=='function')return;d3Form('Reparatur außerhalb Wartungsvertrag',[{name:'date',label:'Datum',type:'date'},{name:'description',label:'Ausgeführte Reparatur',type:'textarea'}],{date:localDate(),description:''},async v=>{if(!v.description.trim())throw new Error('Bitte Reparatur beschreiben.');await api(chefPayload({action:'addMaintenanceRepair',deviceId,date:v.date,description:v.description}));if(S.customer?.id){const fresh=await api(chefPayload({action:'getMaintenanceCustomer',id:S.customer.id}));d37RenderCustomerForm('d37CustomerEditHost',fresh,'edit');}});};

/* ---------- Wartungsbereich ---------- */
function d37MaintenanceShell(){
  const card=$('d36Maintenance');if(!card)return;
  const body=card.querySelector(':scope > .dg48-body');if(!body||$('d37MaintenanceNav'))return;
  body.innerHTML='<div id="d37MaintenanceNav" class="d37-maint-nav"><button type="button" data-tab="overview" onclick="return d37MaintenanceTab(\'overview\')">Wartungsübersicht</button><button type="button" data-tab="create" onclick="return d37MaintenanceTab(\'create\')">Kunde anlegen</button><button type="button" data-tab="manage" onclick="return d37MaintenanceTab(\'manage\')">Kunde verwalten</button><button type="button" data-tab="archive" onclick="return d37MaintenanceTab(\'archive\')">Wartungsarchiv</button></div><div id="d37MaintenanceOverview" class="d37-maint-panel"></div><div id="d37MaintenanceCreate" class="d37-maint-panel hidden"><div id="d37CustomerCreateHost"></div></div><div id="d37MaintenanceManage" class="d37-maint-panel hidden"><div class="d37-search"><input id="d37CustomerSearch" placeholder="Kunde, Objekt, Adresse, Gerät oder Seriennummer suchen"><button type="button" class="btn primary" onclick="return d37SearchCustomers()">Suchen</button></div><div id="d37CustomerSearchResults"></div><div id="d37CustomerEditHost" class="hidden"></div></div><div id="d37MaintenanceArchive" class="d37-maint-panel hidden"><div class="d37-search"><input id="d37ArchiveSearch" placeholder="Archiv durchsuchen"><button type="button" class="btn primary" onclick="return d37LoadArchive()">Suchen</button></div><div id="d37ArchiveList"></div></div>';
  d37RenderCustomerForm('d37CustomerCreateHost',d37BlankCustomer(),'create');
  DG3.loaders.d36Maintenance=window.d37LoadMaintenanceOverview;
}
window.d37MaintenanceTab=function(tab){
  document.querySelectorAll('#d37MaintenanceNav [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
  const map={overview:'d37MaintenanceOverview',create:'d37MaintenanceCreate',manage:'d37MaintenanceManage',archive:'d37MaintenanceArchive'};Object.entries(map).forEach(([k,id])=>$(id)?.classList.toggle('hidden',k!==tab));
  if(tab==='overview')d37LoadMaintenanceOverview();if(tab==='manage')d37SearchCustomers();if(tab==='archive')d37LoadArchive();return false;
};
window.d37LoadMaintenanceOverview=async function(){
  d37MaintenanceShell();const host=$('d37MaintenanceOverview');if(!host)return;
  host.innerHTML='<div class="status info">Wartungen werden geladen …</div>';
  try{const data=await api(chefPayload({action:'getMaintenanceOverview'}));S.overview=data||{};d3Count('maintenance',Number(data.currentMonthOpen||0));
    const months=(data.months||[]);host.innerHTML='<div class="d37-overview-head"><div><h3>Wartungen '+esc37(data.windowLabel||'')+'</h3><div class="muted small">Die Kachel zählt nur im aktuellen Monat noch offene, nicht terminierte Wartungen.</div></div><div class="d37-open-count"><span>Aktueller Monat offen</span><strong>'+Number(data.currentMonthOpen||0)+'</strong></div></div><div class="d37-months">'+months.map(m=>'<button type="button" class="d37-month '+(m.current?'current':'')+'" onclick="return d37ShowMonth(\''+esc37(m.key)+'\')"><span>'+esc37(m.label||monthLabel(m.key))+'</span><strong>'+Number(m.openCount||0)+'</strong><small>'+Number(m.scheduledCount||0)+' terminiert</small></button>').join('')+'</div><div id="d37MonthDetail"></div>';const cur=months.find(x=>x.current)||months[Math.min(3,Math.max(0,months.length-1))];if(cur)d37ShowMonth(cur.key);
  }catch(e){host.innerHTML='<div class="status error">'+esc37(e.message)+'</div>';d3Count('maintenance','!');}
};
window.d37ShowMonth=function(key){const m=(S.overview?.months||[]).find(x=>x.key===key),host=$('d37MonthDetail');if(!m||!host)return false;document.querySelectorAll('.d37-month').forEach(b=>b.classList.toggle('selected',(b.textContent||'').includes(m.label||monthLabel(key))));host.innerHTML='<h3>'+esc37(m.label||monthLabel(key))+'</h3>'+((m.items||[]).map(x=>'<div class="report-card d37-maint-item"><div class="d3-head"><strong>🔧 '+esc37(x.customerName)+'</strong><span class="badge">'+(x.scheduled?'Terminiert':'Offen')+'</span></div><div><b>'+esc37(x.objectName)+'</b> · '+esc37(x.address||'')+'</div><div class="report-meta">'+esc37(fmtDevice(x))+(x.serialNumber?' · Seriennr. '+esc37(x.serialNumber):'')+'</div><div class="report-meta">Fällig: '+esc37(monthLabel(x.nextMaintenanceDue))+'</div>'+(x.scheduled?'<div class="status ok">Termin '+esc37(formatDateDE(x.plannedDate))+' · '+esc37((x.employeeNames||[]).join(', '))+'</div>':'<button type="button" class="btn success" onclick="return d37PlanMaintenance(\''+esc37(x.customerId)+'\',\''+esc37(x.objectId)+'\',\''+esc37(x.deviceId)+'\')">Wartung terminieren</button>')+'</div>').join('')||'<div class="status ok">In diesem Monat sind keine Wartungen fällig.</div>');return false;};
window.d37PlanMaintenance=function(customerId,objectId,deviceId){const all=(S.overview?.months||[]).flatMap(m=>m.items||[]),x=all.find(r=>r.deviceId===deviceId);if(!x)return alert('Wartungsgerät bitte neu laden.');S.plannerLink={customerId,objectId,deviceId};window.dg62New();setTimeout(async()=>{S.plannerLink={customerId,objectId,deviceId};$('d36PlannerType').value='Wartung';$('dg62Customer').value=x.customerName||'';$('dg62Address').value=x.address||'';$('dg62Task').value='Wartung '+fmtDevice(x)+(x.serialNumber?' · Seriennummer '+x.serialNumber:'');if(x.nextMaintenanceDue&&/^\d{4}-\d{2}$/.test(x.nextMaintenanceDue)){$('dg62ED').value=x.nextMaintenanceDue+'-01';}await d37RepairPlannerAssignment();$('dg62MT').textContent='Wartung terminieren';},0);return false;};
window.d37SearchCustomers=async function(){const host=$('d37CustomerSearchResults');if(!host)return false;try{const rows=await api(chefPayload({action:'searchMaintenanceCustomers',query:val('d37CustomerSearch')}));host.innerHTML=(rows||[]).map(x=>'<button type="button" class="d37-search-result" onclick="return d37OpenCustomer(\''+esc37(x.id)+'\')"><strong>'+esc37(x.name)+'</strong><span>'+Number(x.objectCount||0)+' Objekt(e) · '+Number(x.deviceCount||0)+' Gerät(e)</span><small>'+esc37(x.billingCity||'')+'</small></button>').join('')||'<div class="muted">Keine Kunden gefunden.</div>';}catch(e){host.innerHTML='<div class="status error">'+esc37(e.message)+'</div>';}return false;};
window.d37OpenCustomer=async function(id){try{const c=await api(chefPayload({action:'getMaintenanceCustomer',id}));S.customer=c;$('d37CustomerEditHost').classList.remove('hidden');d37RenderCustomerForm('d37CustomerEditHost',c,'edit');$('d37CustomerEditHost').scrollIntoView({behavior:'instant',block:'start'});}catch(e){d37Notice(e.message,'error');}return false;};
window.d37LoadArchive=async function(){const host=$('d37ArchiveList');if(!host)return false;host.innerHTML='<div class="status info">Archiv wird geladen …</div>';try{const rows=await api(chefPayload({action:'getMaintenanceArchive',query:val('d37ArchiveSearch')}));host.innerHTML=(rows||[]).map((x,i)=>'<div class="report-card '+(i%2?'d3-alt':'')+'"><div class="d3-head"><strong>'+esc37(x.kind==='Repair'?'🔧 Reparatur':'🧾 Wartungsbericht')+' · '+esc37(x.customerName)+'</strong><span class="badge">'+esc37(formatDateDE(x.date))+'</span></div><div>'+esc37(x.objectName||'')+' · '+esc37(x.deviceLabel||'')+'</div><div class="report-meta">'+esc37(x.description||'')+'</div>'+(x.employee?'<div class="small muted">Mitarbeiter: '+esc37(x.employee)+'</div>':'')+'</div>').join('')||'<div class="status ok">Noch keine Archiv-Einträge.</div>';}catch(e){host.innerHTML='<div class="status error">'+esc37(e.message)+'</div>';}return false;};

/* ---------- Installation / Kachelzählung ---------- */
const baseInstall37=window.d3InstallOffice;
if(typeof baseInstall37==='function')window.d3InstallOffice=d3InstallOffice=function(){const r=baseInstall37.apply(this,arguments);d37MaintenanceShell();return r;};
const baseDashboard37=window.d3Dashboard;
if(typeof baseDashboard37==='function')window.d3Dashboard=d3Dashboard=async function(){const r=await baseDashboard37.apply(this,arguments);if(canAccessBoss()&&navigator.onLine){try{const o=await api(chefPayload({action:'getMaintenanceOverview'}));d3Count('maintenance',Number(o.currentMonthOpen||0));S.overview=o;}catch(_e){d3Count('maintenance','!');}}return r;};
const baseOpen37=window.d3Open;
if(typeof baseOpen37==='function')window.d3Open=d3Open=function(id,child){const r=baseOpen37.apply(this,arguments);if(id==='d36Maintenance')setTimeout(()=>{d37MaintenanceShell();d37LoadMaintenanceOverview();$('d36Maintenance')?.scrollIntoView({behavior:'instant',block:'start'});},0);return r;};
const baseStartup37=window.d3Startup;
if(typeof baseStartup37==='function')window.d3Startup=d3Startup=function(){const r=baseStartup37.apply(this,arguments);setTimeout(()=>{d37MaintenanceShell();d37RepairPlannerAssignment();},0);return r;};
})();
