/* DG 3.0 office: one menu state, one report renderer, scoped selection. */
function d3Body(c){return c?.querySelector(':scope > .dg48-body');}
function d3Collapse(c,closed){d3Body(c)?.classList.toggle('hidden',closed);const h=c.querySelector(':scope > .dg48-head'),b=h?.querySelector('button');if(b)b.textContent=closed?'+':'\u2212';if(h)h.setAttribute('aria-expanded',String(!closed));const d=c.querySelector(':scope > details');if(d)d.open=!closed;}
function d3Section(id,title,html=''){const c=d3Element('div','card','<div class="dg48-head" tabindex="0" role="button"><h2>'+esc(title)+'</h2><button class="dg48-toggle" type="button" tabindex="-1">+</button></div><div class="dg48-body hidden">'+html+'</div>');c.id=id;return c;}
function d3Open(id,child){const c=$(id);if(!c)return;[...$('bossView').children].filter(x=>x.classList.contains('card')).forEach(x=>d3Collapse(x,x!==c));if(child){c.querySelectorAll('.d3-panel').forEach(x=>x.classList.toggle('hidden',x.id!==child));c.querySelectorAll('[data-panel]').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.panel===child)));}DG3.open=child||id;const fn=DG3.loaders[DG3.open];if(fn)Promise.resolve(fn()).catch(e=>d3Notice(e.message,'error'));}
function d3Wire(c){const old=c.querySelector(':scope > .dg48-head');if(!old)return;const h=old.cloneNode(true);old.replaceWith(h);h.tabIndex=0;const go=e=>{if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;e.preventDefault();e.stopPropagation();if(d3Body(c).classList.contains('hidden'))d3Open(c.id);else{d3Collapse(c,true);DG3.open='';}};h.addEventListener('click',go);h.addEventListener('keydown',go);}
function d3Group(id,title,items){const c=d3Section(id,title,'<div class="d3-menu"></div><div class="d3-content"></div>'),menu=c.querySelector('.d3-menu'),host=c.querySelector('.d3-content');items.forEach(([p,label])=>{if(!p)return;p.classList.add('d3-panel','hidden');p.querySelector(':scope > .dg48-head')?.remove();d3Body(p)?.classList.remove('hidden');const b=d3Element('button','',esc(label));b.type='button';b.dataset.panel=p.id;b.addEventListener('click',()=>{const y=menu.getBoundingClientRect().top;host.style.minHeight=Math.max(0,innerHeight-host.getBoundingClientRect().top)+'px';d3Open(id,p.id);const delta=menu.getBoundingClientRect().top-y;if(Math.abs(delta)>1)window.scrollBy({top:delta,behavior:'instant'});});menu.append(b);host.append(p);});return c;}
function d3InstallOffice(){const root=$('bossView'),cards=[...root.children],find=t=>cards.find(c=>(c.querySelector(':scope > .dg48-head h2,:scope > h2')?.textContent||'').includes(t));const completed=find('Regieberichte');completed.id='d3Completed';completed.querySelector('h2').textContent='Abgeschlossene Auftr\u00e4ge';$('regieMergeToolbar')?.remove();
 const running=d3Section('d3Running','Laufende Auftr\u00e4ge','<div id="d3RunningStatus"></div><div id="d3OrderPlan"></div><div id="d3RunningList"></div>');
 const inquiry=d3Section('d3Inquiries','Offene Anfragen','<div class="report-actions">'+d3Button('Gmail abgleichen','d3Import')+d3Button('Aktualisieren','d3Inquiries',[],'secondary')+'</div><div id="d3InquiryStatus"></div><div id="d3InquiryList"></div>');
 const offers=[['d3OfferOpen','Offene Angebote','Offen'],['d3OfferCreate','Angebote zu erstellen','Zu erstellen'],['d3OfferArchive','Angebotsarchiv','Archiv']].map(([id,title,stage])=>{const p=d3Section(id,title,'<h3>'+title+'</h3><div id="'+id+'Status"></div><div id="'+id+'List"></div>');DG3.loaders[id]=()=>loadOffers(stage);return [p,title];});const stat=d3Section('d3Stats','Angebotsstatistik','<div id="d3StatsStatus"></div><div id="d3StatsList"></div>');offers.push([stat,'Angebotsstatistik']);DG3.loaders.d3Stats=loadStats;const offerGroup=d3Group('d3Offers','Angebotsbereich',offers);
 const reminder=d3Section('d3Reminder','Reminder','<div id="d3ReminderStatus"></div><div id="d3ReminderList"></div>'),employee=find('Mitarbeiterverwaltung');employee.id='d3EmployeeAdmin';const admin=d3Group('d3Admin','Verwaltung',[[employee,'Mitarbeiterverwaltung'],[$('dg48AbsenceGroup'),'Urlaub / Abwesenheiten / Feiertage'],[$('dg48EmployeeClosures'),'Mitarbeiterberichte']]),health=d3Section('d3Health','Systemcheck','<div id="d3HealthList"></div>'),planner=$('dg62PlannerCard');
 [planner,completed,running,inquiry,offerGroup,reminder,admin,health].forEach((c,i)=>{root.append(c);c.classList.add('d3-main');c.classList.toggle('d3-alt',i%2===1);if(c!==planner)d3Wire(c);d3Collapse(c,true);});
 Object.assign(DG3.loaders,{d3Completed:()=>loadRegieReports(DG3.completedView||'Abgeschlossen'),d3Running:()=>loadRegieReports('Laufend'),d3Inquiries:d3Inquiries,d3Reminder:loadReminders,d3EmployeeAdmin:loadChefAdministration,dg48AbsenceGroup:loadChefAdministration,dg48EmployeeClosures:loadBossDayClosuresV48,d3Health:d3Health,dg62PlannerCard:()=>dg62Load()});
 const details=planner.querySelector('.dg62-main');details.addEventListener('toggle',()=>{if(details.open){[...root.children].filter(x=>x.classList.contains('card')&&x!==planner).forEach(x=>d3Collapse(x,true));DG3.open=planner.id;dg62Load();}});
 const tiles=[['completed','Abgeschlossene Auftr\u00e4ge','d3Completed',''],['running','Laufende Auftr\u00e4ge','d3Running',''],['offers','Offene Angebote','d3Offers','d3OfferOpen'],['days','Offene Tagesabschl\u00fcsse','d3Admin','dg48EmployeeClosures'],['reminders','Reminder','d3Reminder',''],['inquiries','Offene Anfragen','d3Inquiries','']];root.prepend(d3Element('div','d3-dashboard',tiles.map(([key,label,id,sub])=>'<button type="button" class="d3-tile '+key+'" data-d3-fn="d3Open" data-d3-args="'+esc(JSON.stringify([id,sub]))+'"><span>'+esc(label)+'</span><strong id="d3Count-'+key+'">\u2026</strong></button>').join('')));root.prepend(d3Element('div','muted small','<div id="d3Sync">Automatische Aktualisierung bereit</div>'));
}
function d3Count(k,v){const e=$('d3Count-'+k);if(e&&e.textContent!==String(v))e.textContent=String(v);}
async function d3Dashboard(){if(!canAccessBoss()||!navigator.onLine)return;const d=new Date(),jobs=[['reports',{action:'getRegieReports',status:'Offen',year:0,month:0}],['offers',{action:'getOfferReports',stage:'Offen'}],['days',{action:'getBossDayClosures',year:d.getFullYear(),month:d.getMonth()+1}],['reminders',{action:'getOfferReminders',includeDone:false}],['inquiries',{action:'getCustomerInquiries',status:'Offen'}]];await Promise.all(jobs.map(async([k,p])=>{try{const a=await api(chefPayload(p));if(k==='reports'){d3Count('running',a.filter(g=>g.jobStatus==='Laufend').length);d3Count('completed',a.filter(g=>g.jobStatus!=='Laufend').length);}else d3Count(k,k==='days'?a.reduce((n,x)=>n+(x.days||[]).filter(d=>!d.closed).length,0):k==='reminders'?a.filter(x=>x.isDue).length:a.length);}catch(e){if(k==='reports'){d3Count('running','!');d3Count('completed','!');}else d3Count(k,'!');}}));}
function d3ReportRoot(view){return $(view==='Laufend'?'d3RunningList':'regieResult');}
async function d3Reports(view='Abgeschlossen'){DG3.active=view;window.__regieStatus=view;if(view!=='Laufend')DG3.completedView=view;const root=d3ReportRoot(view),st=view==='Laufend'?'d3RunningStatus':'regieStatus',billed=view==='Abgerechnet';DG3.tokens=DG3.tokens||{};const token=DG3.tokens[root.id]=(DG3.tokens[root.id]||0)+1;if(view!=='Laufend')$('regieDateFilter')?.classList.toggle('hidden',!billed);if(!navigator.onLine){setMessage(st,'Offline. Angezeigte Daten sind moeglicherweise veraltet.','warn');return;}setMessage(st,'Auftr\u00e4ge werden geladen ...','info');try{const data=await api(chefPayload({action:'getRegieReports',status:billed?'Abgerechnet':'Offen',year:billed?(+$('regieYear').value||0):0,month:billed?(+$('regieMonth').value||0):0}));if(DG3.tokens[root.id]!==token)return;const groups=data.filter(g=>billed||(view==='Laufend'?g.jobStatus==='Laufend':g.jobStatus!=='Laufend'));DG3.reports[view]=groups;root.replaceChildren();if(!billed&&groups.length)root.append(d3Element('div','d3-merge-top',d3Button('Ausgew\u00e4hlte zusammenf\u00fchren','requestMergeSelectedRegieReports',[view],'success')+'<div class="muted small d3-hint">Mindestens zwei Kundenkarten markieren.</div>'));groups.forEach((g,i)=>root.append(d3ReportCard(g,view,i)));if(!groups.length)root.innerHTML='<div class="status ok">Keine Eintr\u00e4ge.</div>';setMessage(st,groups.length+' Kundenkarte(n) geladen - '+new Date().toLocaleTimeString('de-DE'),'ok');if(view==='Laufend')await d3Orders();}catch(e){setMessage(st,'Laden fehlgeschlagen: '+e.message,'error');}}
function d3Single(r){return '<div class="entry"><strong>'+esc(formatDateDE(r.date))+' - '+esc(r.employee)+' - '+formatHours(r.hours)+' Std.</strong><div>'+esc(r.start)+' - '+esc(r.end)+'</div><div>'+esc(r.activity||'')+'</div>'+(r.materialUsed?'<div>Material: '+esc(r.material)+'</div>':'')+(r.isSupplement?'<div class="status info">Nachtrag '+esc(r.supplementCreatedAt||'')+'</div>':'')+'</div>';}
function d3ReportCard(g,view,index){const billed=view==='Abgerechnet',ids=[...new Set((g.objectIds||[g.objectId]).filter(Boolean))],reports=(g.reports||[]).filter(x=>x.id),key=view+':'+index,c=d3Element('div','report-card '+(billed?'billed':'open')+(index%2?' d3-alt':''));c.dataset.index=index;c.dataset.view=view;window.__dgGroupMap[key]=reports.map(x=>String(x.id));reports.forEach(r=>window.__dgReportMap[String(r.id)]=r);const state=billed?'Abgerechnet':view==='Laufend'?'Laufend':'Abgeschlossen';c.innerHTML=(!billed?'<label class="d3-selection"><input type="checkbox" class="regie-merge-select" data-index="'+index+'" data-object-ids="'+esc(ids.join(','))+'"> Zum Zusammenf\u00fchren markieren</label>':'')+'<div class="d3-head"><strong>\ud83c\udfe2 '+esc(g.customer)+'</strong><span class="job-status '+(billed?'billed':view==='Laufend'?'running':'completed')+'">'+state+'</span></div><div class="report-meta">'+esc(formatDateDE(g.firstDate))+(g.lastDate!==g.firstDate?' bis '+esc(formatDateDE(g.lastDate)):'')+' - '+reports.length+' Bericht(e)</div><div class="total">Gesamt Personal: '+formatHours(g.totalHours)+' Std.</div><div class="report-meta"><strong>Mitarbeiter:</strong> '+esc((g.employees||[]).join(', '))+'</div><details><summary>Einzelberichte anzeigen</summary>'+reports.map(d3Single).join('')+'</details>';
 const photos=new Map();reports.forEach(r=>{const p=String(r.photoFileIds||'').split(','),u=String(r.photoUrls||'').split(' | ');p.forEach((id,i)=>{if(id.trim())photos.set(id.trim(),u[i]||'');});});c.append(d3Element('div','d3-export','<strong>Bericht herunterladen</strong><div class="muted small">Exportiert genau die '+reports.length+' angezeigten Einzelberichte mit Unterschriften und ausgew\u00e4hlten Bildern.</div>'+[...photos].map(([id,u],i)=>'<label class="d3-selection"><input type="checkbox" class="d3-photo" value="'+esc(id)+'" checked> Bild '+(i+1)+' <a target="_blank" rel="noopener" href="'+esc(u)+'">ansehen</a></label>').join('')+d3Button('Bericht herunterladen','d3Export',[view,index])+'<div class="d3-export-status"></div>'));
 const b=[d3Button('Bericht bearbeiten','dgRequestGroupEdit',[key])];if(!billed){b.push(d3Button(view==='Laufend'?'Auftrag abschlie\u00dfen':'Auf laufend zur\u00fccksetzen','setRegieObjectJobStatus',[ids.join(','),view==='Laufend'?'Abgeschlossen':'Laufend'],'success'));if(view==='Abgeschlossen')b.push(d3Button('Als abgerechnet markieren','markRegieObjectBilled',[ids.join(',')],'success'));b.push(d3Button('Angebot zu erstellen','d3MoveOffer',[reports.map(x=>x.id)]));}b.push(d3Button('Interner Vermerk','d3Note',[ids[0],g.customer]));if(!billed)b.push(d3Button('Ausgew\u00e4hlte zusammenf\u00fchren','requestMergeSelectedRegieReports',[view],'success'));c.append(d3Element('div','report-actions',b.join('')));if(billed)c.append(d3Element('div','status info','Abgerechnet am '+esc(g.billedAt||'')+' von '+esc(g.billedBy||'')));c.querySelector('.regie-merge-select')?.addEventListener('change',()=>updateRegieMergeButton(view));return c;}
function d3Merge(view){const root=d3ReportRoot(view);if(!d3Visible(root))return;const checked=[...root.querySelectorAll('.regie-merge-select:checked')];if(checked.length<2)return alert('Mindestens zwei unterschiedliche Kundenkarten markieren.');const groups=checked.map(x=>DG3.reports[view][+x.dataset.index]),ids=[...new Set(groups.flatMap(g=>g.objectIds||[g.objectId]))].filter(Boolean);if(ids.length<2)return alert('Auswahl enthaelt nur ein gemeinsames Objekt.');DG3.merge={view,ids};$('regieMergeConfirmText').textContent='Diese '+groups.length+' Kundenkarten zusammenfuehren?\n\n'+groups.map(g=>g.customer).join('\n')+'\n\nEinzelberichte und Stunden bleiben erhalten.';$('regieMergeConfirmModal').classList.remove('hidden');}
async function d3ConfirmMerge(){if(DG3.merging||!DG3.merge)return;DG3.merging=true;const {view,ids}=DG3.merge;try{await api(chefPayload({action:'mergeRegieObjects',objectIds:ids}));closeRegieMergeConfirm();await d3Reports(view);setMessage(view==='Laufend'?'d3RunningStatus':'regieStatus','Ausgewaehlte Berichte zusammengefuehrt.','ok');}catch(e){alert('Zusammenfuehren fehlgeschlagen: '+e.message);}finally{DG3.merging=false;}}
async function d3Export(view,index){const g=DG3.reports[view]?.[index];if(!g)throw new Error('Bitte Berichte neu laden.');const card=d3ReportRoot(view).querySelector('.report-card[data-index="'+index+'"]'),st=card.querySelector('.d3-export-status');st.className='status info';st.textContent='Export wird erstellt ...';try{const r=await api(chefPayload({action:'createRegieReportZip',objectIds:g.objectIds||[g.objectId],entryIds:g.reports.map(x=>x.id),fileIds:[...card.querySelectorAll('.d3-photo:checked')].map(x=>x.value),customer:g.customer}));d3Download(r,'application/zip');st.className='status ok';st.textContent=r.reportCount+' Berichte exportiert.';}catch(e){st.className='status error';st.textContent=e.message;}}
async function d3JobStatus(ids,status){if(!confirm('Auftrag auf '+status+' setzen?'))return;const view=DG3.active;for(const objectId of ids.split(',').filter(Boolean))await api(chefPayload({action:'setRegieObjectJobStatus',objectId,jobStatus:status}));await d3Reports(view);}
async function d3Bill(ids){const objectIds=ids.split(',').filter(Boolean),risk=await api(chefPayload({action:'checkRegieBillingRisk',objectIds})),matches=risk.matches||[];if(!confirm((matches.length?'Weitere offene Vorgaenge gefunden:\n'+matches.map(x=>x.customer).join('\n')+'\n\n':'')+'Diesen Auftrag als abgerechnet markieren?'))return;await api(chefPayload({action:'markRegieObjectsBilled',objectIds,force:!!matches.length}));await d3Reports(DG3.active);}
async function d3MoveOffer(entryIds){if(!confirm('Nach Angebote zu erstellen verschieben?'))return;await api(chefPayload({action:'setRegieReportsOfferStatus',entryIds,offerStatus:'Angebot zu erstellen'}));await d3Reports(DG3.active);}
async function d3Note(objectId,customer){const r=await api(chefPayload({action:'getObjectInternalNote',objectId})),note=prompt('Interner Vermerk zu '+customer,r.note||'');if(note===null)return;await api(chefPayload({action:'saveObjectInternalNote',objectId,note}));}
async function d3Health(){const out=$('d3HealthList');out.textContent='System wird geprueft ...';try{const r=await api(chefPayload({action:'systemHealthCheck'}));out.innerHTML='<div class="status '+(r.ok?'ok':'warn')+'">App 3.0 - Backend '+esc(r.version)+' - '+esc(r.checkedAt)+'</div>'+(r.checks||[]).map(x=>'<div class="status '+(x.level==='error'?'error':x.level==='warn'?'warn':'ok')+'"><strong>'+esc(x.name)+'</strong><br>'+esc(x.detail)+'</div>').join('');}catch(e){out.textContent='Systemcheck fehlgeschlagen: '+e.message;}}
