/* DG 3.0: one request coordinator and one synchronization clock. */
window.DG3={version:'3.0',backend:'',pending:0,reads:new Map(),reports:{},active:'Abgeschlossen',loaders:{},ready:false};window.DG_APP_VERSION='3.0';
function d3Visible(e){return !!(e&&e.getClientRects().length);}
function d3Notice(msg,type='info'){let e=$('d3Notice');if(!e){e=document.createElement('div');e.id='d3Notice';document.querySelector('#mainScreen .tabs').after(e);}e.className='status '+type;e.textContent=msg;}
function d3Button(text,fn,args=[],kind='primary'){return '<button type="button" class="btn '+kind+'" data-d3-fn="'+esc(fn)+'" data-d3-args="'+esc(JSON.stringify(args))+'">'+esc(text)+'</button>';}
async function d3CheckBackend(){try{const r=await api({action:'ping'});DG3.backend=String(r.version||'');if(!/^3\./.test(DG3.backend))d3Notice('App 3.0: Bitte zuerst Google-GS 3.0 bereitstellen. Backend: '+DG3.backend+'. Speichern ist gesperrt.','warn');else $('d3Notice')?.remove();return /^3\./.test(DG3.backend);}catch(e){d3Notice('Verbindungspruefung fehlgeschlagen: '+e.message,'warn');return false;}}
async function d3Api(payload){const action=String(payload.action||''),read=/^(get|check)/.test(action)||['ping','employeeLogin','systemHealthCheck'].includes(action),key=JSON.stringify(payload);if(action!=='ping'&&!/^3\./.test(DG3.backend)){await d3CheckBackend();if(!/^3\./.test(DG3.backend))throw dgError('Google-Backend 3.0 noch nicht bereitgestellt.','version');}if(read&&DG3.reads.has(key))return DG3.reads.get(key);const promise=(async()=>{if(!read)DG3.pending++;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),65000);try{let response;try{response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...payload,clientVersion:'3.0'}),signal:controller.signal});}catch(e){throw dgError(e.name==='AbortError'?'Serverantwort dauert zu lange. Vor erneutem Anlegen zuerst Daten neu laden.':'Keine Serververbindung.','network');}if(!response.ok)throw dgError('HTTP '+response.status,'network');let data;try{data=JSON.parse(await response.text());}catch(e){throw dgError('Ungueltige Serverantwort.','server');}if(!data.ok)throw dgError(data.error||'Serverfehler.','server');return data.data!==undefined?data.data:data;}finally{clearTimeout(timer);if(!read)DG3.pending--;}})();if(read)DG3.reads.set(key,promise);try{return await promise;}finally{if(read&&DG3.reads.get(key)===promise)DG3.reads.delete(key);}}
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const fn=b.dataset.d3Fn,handler=fn?window[fn]:b.getAttribute('onclick')?b.onclick:null;if(typeof handler!=='function')return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.d3Busy)return;try{const r=handler.apply(b,fn?JSON.parse(b.dataset.d3Args||'[]'):[e]);if(r&&typeof r.then==='function'){b.dataset.d3Busy='1';b.disabled=true;b.setAttribute('aria-busy','true');Promise.resolve(r).catch(err=>d3Notice(err.message,'error')).finally(()=>{delete b.dataset.d3Busy;b.disabled=false;b.removeAttribute('aria-busy');});}}catch(err){d3Notice(err.message,'error');}},true);
function d3Dirty(){return !!(document.activeElement?.matches('input,textarea,select')||document.querySelector('[data-d3-busy]')||[...document.querySelectorAll('[id$="Modal"],.regie-merge-select:checked')].some(d3Visible)||(($('customer')?.value||'').trim())||(($('activity')?.value||'').trim())||(typeof preparedPhotos!=='undefined'&&preparedPhotos.length));}
async function d3Sync(){if(DG3.syncing||DG3.pending||document.hidden||!navigator.onLine||!DG3.ready||!auth().employee||d3Dirty())return;DG3.syncing=true;try{await syncQueue(false);if(d3Visible($('employeeView'))){await loadDay();await loadCalendarEvents();}else{if(DG3.loaders[DG3.open])await DG3.loaders[DG3.open]();await d3Dashboard();}if($('d3Sync'))$('d3Sync').textContent='Aktualisierung angefordert: '+new Date().toLocaleTimeString('de-DE')+' - Ergebnis im jeweiligen Bereich.';}catch(e){if($('d3Sync'))$('d3Sync').textContent='Aktualisierung fehlgeschlagen: '+e.message;}finally{DG3.syncing=false;}}
function d3Element(tag,cls='',html=''){const e=document.createElement(tag);e.className=cls;e.innerHTML=html;return e;}
function d3Download(r,type){const b=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0)),u=URL.createObjectURL(new Blob([b],{type})),a=document.createElement('a');a.href=u;a.download=r.fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function d3Form(title,fields,values,save){$('d3FormModal')?.remove();const modal=d3Element('div','d3-modal','<form class="d3-form"><h2></h2><div class="d3-fields"></div><div role="status" class="d3-message"></div><div class="report-actions"><button type="submit" class="btn success">Speichern</button><button type="button" class="btn secondary" data-cancel>Abbrechen</button></div></form>');modal.id='d3FormModal';modal.querySelector('h2').textContent=title;const form=modal.querySelector('form'),host=modal.querySelector('.d3-fields'),status=modal.querySelector('.d3-message');fields.forEach(f=>{const label=d3Element('label','',esc(f.label));let input;if(f.type==='workers'){input=d3Element('div','d3-workers');f.options.forEach(w=>{const l=d3Element('label','d3-selection','<input type="checkbox" name="'+esc(f.name)+'" value="'+esc(w.value)+'"> '+esc(w.label));l.querySelector('input').checked=(values[f.name]||[]).includes(w.value);input.append(l);});}else{input=document.createElement(f.type==='textarea'?'textarea':f.type==='select'?'select':'input');if(f.type!=='textarea'&&f.type!=='select')input.type=f.type||'text';if(f.type==='select')f.options.forEach(o=>{const p=typeof o==='string'?{value:o,label:o}:o,x=d3Element('option','',esc(p.label));x.value=p.value;input.append(x);});input.name=f.name;input.id='d3Field-'+f.name;input.value=values[f.name]??'';input.required=!!f.required;label.htmlFor=input.id;}host.append(label,input);});modal.querySelector('[data-cancel]').addEventListener('click',()=>{if(!form.dataset.busy)modal.remove();});form.addEventListener('submit',async e=>{e.preventDefault();if(form.dataset.busy||!form.reportValidity())return;const v={};fields.forEach(f=>v[f.name]=f.type==='workers'?[...form.querySelectorAll('input[name="'+f.name+'"]:checked')].map(x=>x.value):form.elements[f.name].value);form.dataset.busy='1';form.querySelectorAll('button').forEach(x=>x.disabled=true);status.className='status info';status.textContent='Wird gespeichert ...';try{await save(v);modal.remove();}catch(err){status.className='status error';status.textContent=err.message;}finally{delete form.dataset.busy;form.querySelectorAll('button').forEach(x=>x.disabled=false);}});document.body.append(modal);return modal;}
