DG3.offers={};DG3.inquiries=[];DG3.orders=[];DG3.reminders=[];
function d3OfferBox(stage){return stage==='Offen'?'d3OfferOpen':stage==='Zu erstellen'?'d3OfferCreate':'d3OfferArchive';}
async function loadOffers(stage='Offen'){const id=d3OfferBox(stage);setMessage(id+'Status','Angebote werden geladen ...','info');try{const rows=await api(chefPayload({action:'getOfferReports',stage}));DG3.offers[stage]=rows;$(id+'List').innerHTML=rows.map((r,i)=>{const buttons=stage==='Offen'?d3Button('Angenommen','d3OfferDecision',[r.offerId,true],'success')+d3Button('Abgelehnt','d3OfferDecision',[r.offerId,false],'secondary'):stage==='Zu erstellen'?d3Button('Angebot erstellt','d3OfferCreated',[r.offerId],'success')+d3Button('Auftrag entfernen','d3DiscardOffer',[r.offerId],'danger'):'';return '<div class="report-card'+(i%2?' d3-alt':'')+'"><strong>'+esc(r.customer)+'</strong><div class="report-meta">'+esc(r.status)+' - '+Number(r.reportCount||0)+' Berichte - '+formatHours(r.totalHours)+' Std.</div><div>'+esc(r.description||'')+'</div>'+((r.reports||[]).length?'<details><summary>Einzelberichte anzeigen</summary>'+r.reports.map(d3Single).join('')+'</details>':'<div class="muted small">Angebot ohne bereits erfasste Arbeitszeit.</div>')+'<div class="report-actions">'+buttons+'</div></div>';}).join('')||'Keine Angebote vorhanden.';setMessage(id+'Status',rows.length+' Angebot(e) geladen.','ok');if(stage==='Offen')d3Count('offers',rows.length);}catch(e){setMessage(id+'Status',e.message,'error');}}
function d3Offer(id){for(const list of Object.values(DG3.offers)){const r=list.find(x=>x.offerId===id);if(r)return r;}throw new Error('Angebot nicht mehr aktuell. Bitte neu laden.');}
async function d3OfferDecision(offerId,yes){const r=d3Offer(offerId),running=yes&&r.totalHours>0?confirm('Mit Arbeitszeit als laufenden Auftrag uebernehmen?\nOK = Laufender Auftrag\nAbbrechen = angenommen archivieren'):false;if(!confirm('Angebot '+(yes?'annehmen':'ablehnen')+'?'))return;await api(chefPayload(running?{action:'acceptOfferAsRunning',offerId}:{action:'setRegieReportsOfferStatus',offerId,entryIds:[],offerStatus:yes?'Angebot Angenommen':'Angebot Abgelehnt'}));await loadOffers('Offen');}
function d3OfferCreated(offerId){const r=d3Offer(offerId);d3Form('Angebot erstellt - Reminder in 5 Tagen',[{name:'customer',label:'Kunde',required:true},{name:'offerNumber',label:'Angebotsnummer',required:true},{name:'phone',label:'Telefon'},{name:'email',label:'E-Mail',type:'email'},{name:'description',label:'Beschreibung',type:'textarea'}],r,async item=>{await api(chefPayload({action:'saveOfferCreatedWithReminder',offerId,item}));await loadOffers('Zu erstellen');});}
async function d3DiscardOffer(offerId){if(!confirm('Noch nicht erstellten Angebotsvorgang entfernen? Arbeitszeiten bleiben im Nachweis erhalten.'))return;await api(chefPayload({action:'discardOfferPermanently',offerId}));await loadOffers('Zu erstellen');}
async function loadStats(){setMessage('d3StatsStatus','Statistik wird geladen ...','info');try{const x=await api(chefPayload({action:'getOfferStatistics'}));$('d3StatsList').innerHTML='<div class="d3-stats">'+[['Erstellt',x.total],['Offen',x.open],['Angenommen',x.accepted],['Abgelehnt',x.declined],['Annahmequote',Number(x.acceptanceRate||0).toFixed(1)+' %']].map(([k,v])=>'<div class="d3-stat"><span>'+k+'</span><strong>'+esc(v??0)+'</strong></div>').join('')+'</div>'+((x.months||[]).length?'<h3>Monatsuebersicht</h3>'+x.months.map(m=>'<div class="entry">'+esc(m.month)+' - '+m.total+' erstellt - '+m.accepted+' angenommen - '+m.declined+' abgelehnt</div>').join(''):'');setMessage('d3StatsStatus','Statistik aktuell.','ok');}catch(e){setMessage('d3StatsStatus',e.message,'error');}}
async function loadReminders(){setMessage('d3ReminderStatus','Reminder werden geladen ...','info');try{DG3.reminders=await api(chefPayload({action:'getOfferReminders',includeDone:false}));$('d3ReminderList').innerHTML=DG3.reminders.map((r,i)=>'<div class="report-card'+(i%2?' d3-alt':'')+'"><strong>'+esc(r.customer)+' - '+esc(r.offerNumber)+'</strong><div class="status '+(r.isOverdue?'warn':'info')+'">Faellig: '+esc(formatDateDE(r.dueDate))+'</div><div>'+esc(r.description)+'</div><div>Telefon: <a href="tel:'+esc(r.phone)+'">'+esc(r.phone)+'</a></div><div class="report-actions">'+d3Button('Angenommen','d3ReminderDecision',[r.id,true],'success')+d3Button('Kein Auftrag','d3ReminderDecision',[r.id,false],'secondary')+d3Button('Verschieben','d3ReminderDate',[r.id])+'</div></div>').join('')||'Keine offenen Reminder.';setMessage('d3ReminderStatus',DG3.reminders.length+' offene Reminder.','ok');d3Count('reminders',DG3.reminders.filter(x=>x.isDue).length);}catch(e){setMessage('d3ReminderStatus',e.message,'error');}}
async function d3ReminderDecision(id,yes){const r=DG3.reminders.find(x=>x.id===id);if(!r)throw new Error('Bitte neu laden.');const asRunning=yes&&r.totalHours>0?confirm('Als laufenden Auftrag uebernehmen? OK=laufend, Abbrechen=angenommen archivieren.'):false;if(!confirm(yes?'Angebot annehmen?':'Angebot ablehnen?'))return;await api(chefPayload({action:yes?'acceptOfferFromReminder':'declineOfferFromReminder',reminderId:id,asRunning}));await loadReminders();}
function d3ReminderDate(id){const r=DG3.reminders.find(x=>x.id===id);d3Form('Reminder verschieben',[{name:'dueDate',label:'Neues Datum',type:'date',required:true}],r,async v=>{await api(chefPayload({action:'rescheduleOfferReminder',reminderId:id,dueDate:v.dueDate,days:0}));await loadReminders();});}
function d3Inquiry(id){const r=DG3.inquiries.find(x=>x.id===id);if(!r)throw new Error('Anfrage nicht mehr aktuell. Bitte neu laden.');return r;}
function d3Address(r){return r.address||[r.postalCode,r.city].filter(Boolean).join(' ');}
async function d3Inquiries(){setMessage('d3InquiryStatus','Anfragen werden geladen ...','info');try{DG3.inquiries=await api(chefPayload({action:'getCustomerInquiries',status:'Offen'}));$('d3InquiryList').innerHTML=DG3.inquiries.map((r,i)=>'<div class="report-card'+(i%2?' d3-alt':'')+'"><div class="d3-head"><strong>'+esc(r.customer)+'</strong><span class="badge">'+esc(r.source)+'</span></div><div class="report-meta">'+esc(r.receivedAt)+' - '+esc(r.status)+'</div><div>'+esc(d3Address(r))+'</div><div><a href="tel:'+esc(r.phone)+'">'+esc(r.phone)+'</a> <a href="mailto:'+esc(r.email)+'">'+esc(r.email)+'</a></div><div>'+esc(r.description||r.subject)+'</div>'+(r.internalNote?'<div class="status info">Interne Notiz: '+esc(r.internalNote)+'</div>':'')+'<div class="report-actions">'+d3Button('Kontakt aufgenommen','d3Contact',[r.id])+d3Button('Termin erstellen','d3Appointment',['inquiry',r.id,false])+d3Button('Angebot / Besichtigung','d3Appointment',['inquiry',r.id,true])+d3Button('Als Angebot uebernehmen','d3InquiryOffer',[r.id])+d3Button('Als Auftrag uebernehmen','d3InquiryOrder',[r.id],'success')+d3Button('Interne Notiz','d3InquiryNote',[r.id])+d3Button('Erledigt','d3CompleteInquiry',[r.id],'success')+d3Button('Entfernen','d3DeleteInquiry',[r.id],'danger')+'</div></div>').join('')||'Keine offenen Anfragen.';setMessage('d3InquiryStatus',DG3.inquiries.length+' offene Anfragen.','ok');d3Count('inquiries',DG3.inquiries.length);}catch(e){setMessage('d3InquiryStatus',e.message,'error');}}
async function d3Import(){setMessage('d3InquiryStatus','Gmail: Website und CHECK24 werden abgeglichen ...','info');try{const r=await api(chefPayload({action:'syncCustomerInquiries'}));await d3Inquiries();setMessage('d3InquiryStatus','Abgleich: '+Number(r.imported||0)+' neu, '+Number(r.updated||0)+' ergaenzt.','ok');}catch(e){setMessage('d3InquiryStatus',e.message,'error');}}
function d3InquiryNote(id){const r=d3Inquiry(id);d3Form('Interne Notiz',[{name:'note',label:'Notiz',type:'textarea'}],{note:r.internalNote||''},async v=>{await api(chefPayload({action:'saveCustomerInquiryNote',id,note:v.note}));await d3Inquiries();});}
function d3Contact(id){const r=d3Inquiry(id);d3Form('Kontakt dokumentieren',[{name:'date',label:'Datum',type:'date',required:true},{name:'time',label:'Uhrzeit',type:'time',required:true},{name:'person',label:'Gespraechspartner'},{name:'note',label:'Notiz',type:'textarea'}],{date:localDate(),time:new Date().toTimeString().slice(0,5),person:r.customer,note:''},async v=>{await api(chefPayload({action:'saveCustomerInquiryContact',id,...v}));await d3Inquiries();});}
function d3CompleteInquiry(id){const r=d3Inquiry(id);d3Form('Anfrage erledigen',[{name:'reason',label:'Grund',type:'select',options:['Kein Auftrag','Nicht zustaendig','Doppelte Anfrage','Telefonisch erledigt','Kunde meldet sich wieder','Sonstiges']},{name:'note',label:'Interne Notiz',type:'textarea'}],{reason:'Kein Auftrag',note:r.internalNote||''},async v=>{await api(chefPayload({action:'completeCustomerInquiry',id,...v}));await d3Inquiries();});}
async function d3DeleteInquiry(id){if(!confirm('Anfrage aus der offenen Liste entfernen?'))return;await api(chefPayload({action:'deleteCustomerInquiry',id}));await d3Inquiries();}
function d3InquiryOffer(id){d3Form('Als offenes Angebot uebernehmen',[{name:'customer',label:'Kunde',required:true},{name:'phone',label:'Telefon',required:true}],d3Inquiry(id),async v=>{if(v.phone.replace(/\D/g,'').length<6)throw new Error('Gueltige Telefonnummer erforderlich.');await api(chefPayload({action:'inquiryToOffer',id,...v}));await d3Inquiries();});}
async function d3InquiryOrder(id){const r=d3Inquiry(id);if(!confirm('Als Auftrag ohne Termin uebernehmen?'))return;await api(chefPayload({action:'saveManualOrder',item:{id:'AUF-ANF-'+id,customer:r.customer,address:d3Address(r),phone:r.phone,email:r.email,description:r.description||r.subject,source:r.source,inquiryId:r.id,status:'Ohne Termin',internalNote:r.internalNote||''}}));await d3Inquiries();}
async function d3Orders(){DG3.orders=await api(chefPayload({action:'getManualOrders',status:'Alle'}));const rows=DG3.orders.filter(x=>['Ohne Termin','Termin zu vereinbaren','Offen','Laufend'].includes(x.status));$('d3OrderPlan').innerHTML='<div class="d3-head"><strong>Auftragsplanung</strong>'+d3Button('+ Auftrag anlegen','d3NewOrder',[],'success')+'</div>'+rows.map((r,i)=>'<div class="report-card'+(i%2?' d3-alt':'')+'"><strong>'+esc(r.customer)+'</strong> <span class="badge">'+esc(r.status)+'</span><div>'+esc(r.address)+'</div><div>'+esc(r.description)+'</div>'+(r.internalNote?'<div class="status info">'+esc(r.internalNote)+'</div>':'')+'<div class="report-actions">'+d3Button('Termin vereinbaren','d3Appointment',['order',r.id,false])+d3Button('Interne Notiz','d3OrderNote',[r.id])+d3Button(r.status==='Laufend'?'Abschliessen':'Arbeit begonnen','d3OrderStatus',[r.id,r.status==='Laufend'?'Abgeschlossen':'Laufend'],'success')+(r.status!=='Laufend'?d3Button('Entfernen','d3OrderDelete',[r.id],'danger'):'')+'</div></div>').join('');}
function d3NewOrder(){const id='AUF-'+uid();d3Form('Auftrag anlegen',[{name:'customer',label:'Kunde',required:true},{name:'address',label:'Adresse'},{name:'phone',label:'Telefon'},{name:'email',label:'E-Mail',type:'email'},{name:'description',label:'Auftrag',type:'textarea',required:true},{name:'internalNote',label:'Interne Notiz',type:'textarea'}],{},async item=>{await api(chefPayload({action:'saveManualOrder',item:{...item,id,status:'Ohne Termin',source:'Manuell'}}));await d3Orders();});}
function d3OrderNote(id){const r=DG3.orders.find(x=>x.id===id);if(!r)throw new Error('Bitte neu laden.');d3Form('Interne Notiz',[{name:'note',label:'Notiz',type:'textarea'}],{note:r.internalNote||''},async v=>{await api(chefPayload({action:'saveManualOrderNote',id,note:v.note}));await d3Orders();});}
async function d3OrderStatus(id,status){if(!confirm('Auftrag auf '+status+' setzen?'))return;await api(chefPayload({action:'setManualOrderStatus',id,status}));await d3Orders();}
async function d3OrderDelete(id){if(!confirm('Manuellen Auftrag entfernen?'))return;await api(chefPayload({action:'deleteManualOrder',id}));await d3Orders();}
async function d3Appointment(kind,id,offer){const r=kind==='inquiry'?d3Inquiry(id):DG3.orders.find(x=>x.id===id);if(!r)throw new Error('Quelle nicht mehr vorhanden.');const workers=(await api(chefPayload({action:'getPlannerWorkers'}))).filter(x=>x.active),eventId='KT-'+uid();d3Form(offer?'Besichtigung planen':'Termin vereinbaren',[{name:'customer',label:'Kunde',required:true},{name:'address',label:'Vollstaendige Adresse',required:true},{name:'task',label:'Taetigkeit',type:'textarea',required:true},{name:'date',label:'Datum',type:'date',required:true},{name:'start',label:'Von',type:'time',required:true},{name:'end',label:'Bis',type:'time',required:true},{name:'employeeIds',label:'Mitarbeiter',type:'workers',options:workers.map(w=>({value:w.id,label:w.displayName||w.employeeName}))}],{customer:r.customer,address:d3Address(r),task:(offer?'Besichtigung / Angebot: ':'')+(r.description||r.subject||''),date:localDate(),start:'08:00',end:'09:00',employeeIds:[]},async item=>{if(!item.employeeIds.length||item.end<=item.start)throw new Error('Mitarbeiter und Von/Bis pruefen.');await api(chefPayload({action:'planRequest3',kind,id,offer:!!offer,item:{...item,id:eventId}}));if(kind==='inquiry')await d3Inquiries();else await d3Orders();});}
async function d3EditQueue(id){const item=(await queueAll()).find(x=>Number(x.id)===Number(id));if(!item||item.type!=='saveEntry')return;const entry=item.payload.entry;d3Form('Ausstehende Angaben korrigieren',[{name:'customer',label:'Kunde',required:true},{name:'date',label:'Datum',type:'date',required:true},{name:'start',label:'Von',type:'time',required:true},{name:'end',label:'Bis',type:'time',required:true},{name:'activity',label:'Taetigkeit',type:'textarea',required:true}],entry,async v=>{const mins=s=>{const p=s.split(':').map(Number);return p[0]*60+p[1];},a=mins(v.start),b=mins(v.end),duration=(b-a+1440)%1440;if(!duration)throw new Error('Von und Bis duerfen nicht gleich sein.');Object.assign(entry,v,{hours:Math.round(duration/60*100)/100,startMinutes:a,endMinutes:b});delete item.error;await queuePut(item);await renderQueueDetails();});}
